# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'Apiv1CollectionVisibility',
    'Apiv1ShortcutRowStatus',
    'Apiv1ShortcutVisibility',
    'Apiv1UserSettingColorTheme',
    'Apiv1UserSettingLocale',
    'Apiv1WorkspaceSettingDefaultVisibility',
    'Role',
    'RowStatus',
    'V1UserRole',
    'V1UserRowStatus',
    'V1WorkspaceProfilePlan',
    'Visibility',
]


class Apiv1CollectionVisibility(str, Enum):
    VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED"
    PRIVATE = "PRIVATE"
    WORKSPACE = "WORKSPACE"
    PUBLIC = "PUBLIC"


class Apiv1ShortcutRowStatus(str, Enum):
    ROW_STATUS_UNSPECIFIED = "ROW_STATUS_UNSPECIFIED"
    NORMAL = "NORMAL"
    ARCHIVED = "ARCHIVED"


class Apiv1ShortcutVisibility(str, Enum):
    VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED"
    PRIVATE = "PRIVATE"
    WORKSPACE = "WORKSPACE"
    PUBLIC = "PUBLIC"


class Apiv1UserSettingColorTheme(str, Enum):
    COLOR_THEME_UNSPECIFIED = "COLOR_THEME_UNSPECIFIED"
    COLOR_THEME_SYSTEM = "COLOR_THEME_SYSTEM"
    COLOR_THEME_LIGHT = "COLOR_THEME_LIGHT"
    COLOR_THEME_DARK = "COLOR_THEME_DARK"


class Apiv1UserSettingLocale(str, Enum):
    LOCALE_UNSPECIFIED = "LOCALE_UNSPECIFIED"
    LOCALE_EN = "LOCALE_EN"
    LOCALE_ZH = "LOCALE_ZH"
    LOCALE_FR = "LOCALE_FR"


class Apiv1WorkspaceSettingDefaultVisibility(str, Enum):
    VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED"
    PRIVATE = "PRIVATE"
    WORKSPACE = "WORKSPACE"
    PUBLIC = "PUBLIC"


class Role(str, Enum):
    ROLE_UNSPECIFIED = "ROLE_UNSPECIFIED"
    ADMIN = "ADMIN"
    USER = "USER"


class RowStatus(str, Enum):
    ROW_STATUS_UNSPECIFIED = "ROW_STATUS_UNSPECIFIED"
    NORMAL = "NORMAL"
    ARCHIVED = "ARCHIVED"


class V1UserRole(str, Enum):
    ROLE_UNSPECIFIED = "ROLE_UNSPECIFIED"
    ADMIN = "ADMIN"
    USER = "USER"


class V1UserRowStatus(str, Enum):
    ROW_STATUS_UNSPECIFIED = "ROW_STATUS_UNSPECIFIED"
    NORMAL = "NORMAL"
    ARCHIVED = "ARCHIVED"


class V1WorkspaceProfilePlan(str, Enum):
    PLAN_TYPE_UNSPECIFIED = "PLAN_TYPE_UNSPECIFIED"
    FREE = "FREE"
    PRO = "PRO"


class Visibility(str, Enum):
    VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED"
    PRIVATE = "PRIVATE"
    WORKSPACE = "WORKSPACE"
    PUBLIC = "PUBLIC"
