# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetUserSettingServiceUserSettingResult',
    'AwaitableGetUserSettingServiceUserSettingResult',
    'get_user_setting_service_user_setting',
    'get_user_setting_service_user_setting_output',
]

@pulumi.output_type
class GetUserSettingServiceUserSettingResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.V1GetUserSettingResponse':
        return pulumi.get(self, "items")


class AwaitableGetUserSettingServiceUserSettingResult(GetUserSettingServiceUserSettingResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserSettingServiceUserSettingResult(
            items=self.items)


def get_user_setting_service_user_setting(id: Optional[str] = None,
                                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserSettingServiceUserSettingResult:
    """
    Use this data source to access information about an existing resource.

    :param str id: id is the user id.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('slash:api:getUserSettingServiceUserSetting', __args__, opts=opts, typ=GetUserSettingServiceUserSettingResult).value

    return AwaitableGetUserSettingServiceUserSettingResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(get_user_setting_service_user_setting)
def get_user_setting_service_user_setting_output(id: Optional[pulumi.Input[str]] = None,
                                                 opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetUserSettingServiceUserSettingResult]:
    """
    Use this data source to access information about an existing resource.

    :param str id: id is the user id.
    """
    ...
