# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetWorkspaceServiceWorkspaceProfileResult',
    'AwaitableGetWorkspaceServiceWorkspaceProfileResult',
    'get_workspace_service_workspace_profile',
    'get_workspace_service_workspace_profile_output',
]

@pulumi.output_type
class GetWorkspaceServiceWorkspaceProfileResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.V1GetWorkspaceProfileResponse':
        return pulumi.get(self, "items")


class AwaitableGetWorkspaceServiceWorkspaceProfileResult(GetWorkspaceServiceWorkspaceProfileResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkspaceServiceWorkspaceProfileResult(
            items=self.items)


def get_workspace_service_workspace_profile(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkspaceServiceWorkspaceProfileResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('slash:api:getWorkspaceServiceWorkspaceProfile', __args__, opts=opts, typ=GetWorkspaceServiceWorkspaceProfileResult).value

    return AwaitableGetWorkspaceServiceWorkspaceProfileResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(get_workspace_service_workspace_profile)
def get_workspace_service_workspace_profile_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetWorkspaceServiceWorkspaceProfileResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
