# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetWorkspaceServiceWorkspaceSettingResult',
    'AwaitableGetWorkspaceServiceWorkspaceSettingResult',
    'get_workspace_service_workspace_setting',
    'get_workspace_service_workspace_setting_output',
]

@pulumi.output_type
class GetWorkspaceServiceWorkspaceSettingResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.V1GetWorkspaceSettingResponse':
        return pulumi.get(self, "items")


class AwaitableGetWorkspaceServiceWorkspaceSettingResult(GetWorkspaceServiceWorkspaceSettingResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkspaceServiceWorkspaceSettingResult(
            items=self.items)


def get_workspace_service_workspace_setting(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkspaceServiceWorkspaceSettingResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('slash:api:getWorkspaceServiceWorkspaceSetting', __args__, opts=opts, typ=GetWorkspaceServiceWorkspaceSettingResult).value

    return AwaitableGetWorkspaceServiceWorkspaceSettingResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(get_workspace_service_workspace_setting)
def get_workspace_service_workspace_setting_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetWorkspaceServiceWorkspaceSettingResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
