# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ListShortcutServiceShortcutsResult',
    'AwaitableListShortcutServiceShortcutsResult',
    'list_shortcut_service_shortcuts',
    'list_shortcut_service_shortcuts_output',
]

@pulumi.output_type
class ListShortcutServiceShortcutsResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.V1ListShortcutsResponse':
        return pulumi.get(self, "items")


class AwaitableListShortcutServiceShortcutsResult(ListShortcutServiceShortcutsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListShortcutServiceShortcutsResult(
            items=self.items)


def list_shortcut_service_shortcuts(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListShortcutServiceShortcutsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('slash:api:listShortcutServiceShortcuts', __args__, opts=opts, typ=ListShortcutServiceShortcutsResult).value

    return AwaitableListShortcutServiceShortcutsResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(list_shortcut_service_shortcuts)
def list_shortcut_service_shortcuts_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListShortcutServiceShortcutsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
