# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

__all__ = [
    'ListUserServiceUserAccessTokensResult',
    'AwaitableListUserServiceUserAccessTokensResult',
    'list_user_service_user_access_tokens',
    'list_user_service_user_access_tokens_output',
]

@pulumi.output_type
class ListUserServiceUserAccessTokensResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.V1ListUserAccessTokensResponse':
        return pulumi.get(self, "items")


class AwaitableListUserServiceUserAccessTokensResult(ListUserServiceUserAccessTokensResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListUserServiceUserAccessTokensResult(
            items=self.items)


def list_user_service_user_access_tokens(id: Optional[str] = None,
                                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListUserServiceUserAccessTokensResult:
    """
    Use this data source to access information about an existing resource.

    :param str id: id is the user id.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('slash:api:listUserServiceUserAccessTokens', __args__, opts=opts, typ=ListUserServiceUserAccessTokensResult).value

    return AwaitableListUserServiceUserAccessTokensResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(list_user_service_user_access_tokens)
def list_user_service_user_access_tokens_output(id: Optional[pulumi.Input[str]] = None,
                                                opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListUserServiceUserAccessTokensResult]:
    """
    Use this data source to access information about an existing resource.

    :param str id: id is the user id.
    """
    ...
