// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getSubscriptionServiceSubscription(args?: GetSubscriptionServiceSubscriptionArgs, opts?: pulumi.InvokeOptions): Promise<GetSubscriptionServiceSubscriptionResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:subscription/v1:getSubscriptionServiceSubscription", {
    }, opts);
}

export interface GetSubscriptionServiceSubscriptionArgs {
}

export interface GetSubscriptionServiceSubscriptionResult {
    readonly items: outputs.subscription.v1.V1GetSubscriptionResponse;
}
export function getSubscriptionServiceSubscriptionOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetSubscriptionServiceSubscriptionResult> {
    return pulumi.output(getSubscriptionServiceSubscription(opts))
}
