// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../../utilities";

// Export members:
export { GetSubscriptionServiceSubscriptionArgs, GetSubscriptionServiceSubscriptionResult } from "./getSubscriptionServiceSubscription";
export const getSubscriptionServiceSubscription: typeof import("./getSubscriptionServiceSubscription").getSubscriptionServiceSubscription = null as any;
export const getSubscriptionServiceSubscriptionOutput: typeof import("./getSubscriptionServiceSubscription").getSubscriptionServiceSubscriptionOutput = null as any;
utilities.lazyLoad(exports, ["getSubscriptionServiceSubscription","getSubscriptionServiceSubscriptionOutput"], () => require("./getSubscriptionServiceSubscription"));


// Export enums:
export * from "../../types/enums/subscription/v1";
