// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class CollectionServiceCollection extends pulumi.CustomResource {
    /**
     * Get an existing CollectionServiceCollection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CollectionServiceCollection {
        return new CollectionServiceCollection(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'slash:api:CollectionServiceCollection';

    /**
     * Returns true if the given object is an instance of CollectionServiceCollection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CollectionServiceCollection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CollectionServiceCollection.__pulumiType;
    }

    public /*out*/ readonly collection!: pulumi.Output<outputs.api.Apiv1Collection | undefined>;
    public readonly createdTime!: pulumi.Output<string | undefined>;
    public readonly creatorId!: pulumi.Output<number | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly ids!: pulumi.Output<number[] | undefined>;
    public readonly name!: pulumi.Output<string | undefined>;
    public readonly title!: pulumi.Output<string | undefined>;
    public readonly updatedTime!: pulumi.Output<string | undefined>;
    public readonly visibility!: pulumi.Output<enums.api.Visibility | undefined>;

    /**
     * Create a CollectionServiceCollection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CollectionServiceCollectionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["createdTime"] = args ? args.createdTime : undefined;
            resourceInputs["creatorId"] = args ? args.creatorId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["ids"] = args ? args.ids : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["updatedTime"] = args ? args.updatedTime : undefined;
            resourceInputs["visibility"] = (args ? args.visibility : undefined) ?? "VISIBILITY_UNSPECIFIED";
            resourceInputs["collection"] = undefined /*out*/;
        } else {
            resourceInputs["collection"] = undefined /*out*/;
            resourceInputs["createdTime"] = undefined /*out*/;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["ids"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["title"] = undefined /*out*/;
            resourceInputs["updatedTime"] = undefined /*out*/;
            resourceInputs["visibility"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CollectionServiceCollection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CollectionServiceCollection resource.
 */
export interface CollectionServiceCollectionArgs {
    createdTime?: pulumi.Input<string>;
    creatorId?: pulumi.Input<number>;
    description?: pulumi.Input<string>;
    ids?: pulumi.Input<pulumi.Input<number>[]>;
    name?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
    updatedTime?: pulumi.Input<string>;
    visibility?: pulumi.Input<enums.api.Visibility>;
}
