// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getCollectionServiceCollection(args: GetCollectionServiceCollectionArgs, opts?: pulumi.InvokeOptions): Promise<GetCollectionServiceCollectionResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:getCollectionServiceCollection", {
        "id": args.id,
    }, opts);
}

export interface GetCollectionServiceCollectionArgs {
    id: string;
}

export interface GetCollectionServiceCollectionResult {
    readonly items: outputs.api.V1GetCollectionResponse;
}
export function getCollectionServiceCollectionOutput(args: GetCollectionServiceCollectionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCollectionServiceCollectionResult> {
    return pulumi.output(args).apply((a: any) => getCollectionServiceCollection(a, opts))
}

export interface GetCollectionServiceCollectionOutputArgs {
    id: pulumi.Input<string>;
}
