// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getShortcutServiceShortcut(args: GetShortcutServiceShortcutArgs, opts?: pulumi.InvokeOptions): Promise<GetShortcutServiceShortcutResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:getShortcutServiceShortcut", {
        "id": args.id,
    }, opts);
}

export interface GetShortcutServiceShortcutArgs {
    id: string;
}

export interface GetShortcutServiceShortcutResult {
    readonly items: outputs.api.V1GetShortcutResponse;
}
export function getShortcutServiceShortcutOutput(args: GetShortcutServiceShortcutOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetShortcutServiceShortcutResult> {
    return pulumi.output(args).apply((a: any) => getShortcutServiceShortcut(a, opts))
}

export interface GetShortcutServiceShortcutOutputArgs {
    id: pulumi.Input<string>;
}
