// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getWorkspaceServiceWorkspaceSetting(args?: GetWorkspaceServiceWorkspaceSettingArgs, opts?: pulumi.InvokeOptions): Promise<GetWorkspaceServiceWorkspaceSettingResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:getWorkspaceServiceWorkspaceSetting", {
    }, opts);
}

export interface GetWorkspaceServiceWorkspaceSettingArgs {
}

export interface GetWorkspaceServiceWorkspaceSettingResult {
    readonly items: outputs.api.V1GetWorkspaceSettingResponse;
}
export function getWorkspaceServiceWorkspaceSettingOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetWorkspaceServiceWorkspaceSettingResult> {
    return pulumi.output(getWorkspaceServiceWorkspaceSetting(opts))
}
