// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getWorkspaceServiceWorkspaceProfile(args?: GetWorkspaceServiceWorkspaceProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetWorkspaceServiceWorkspaceProfileResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:getWorkspaceServiceWorkspaceProfile", {
    }, opts);
}

export interface GetWorkspaceServiceWorkspaceProfileArgs {
}

export interface GetWorkspaceServiceWorkspaceProfileResult {
    readonly items: outputs.api.V1GetWorkspaceProfileResponse;
}
export function getWorkspaceServiceWorkspaceProfileOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetWorkspaceServiceWorkspaceProfileResult> {
    return pulumi.output(getWorkspaceServiceWorkspaceProfile(opts))
}
