// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetShortcutServiceShortcutArgs, GetShortcutServiceShortcutResult, GetShortcutServiceShortcutOutputArgs } from "./getShortcutServiceShortcut";
export const getShortcutServiceShortcut: typeof import("./getShortcutServiceShortcut").getShortcutServiceShortcut = null as any;
export const getShortcutServiceShortcutOutput: typeof import("./getShortcutServiceShortcut").getShortcutServiceShortcutOutput = null as any;
utilities.lazyLoad(exports, ["getShortcutServiceShortcut","getShortcutServiceShortcutOutput"], () => require("./getShortcutServiceShortcut"));

export { ListShortcutServiceShortcutsArgs, ListShortcutServiceShortcutsResult } from "./listShortcutServiceShortcuts";
export const listShortcutServiceShortcuts: typeof import("./listShortcutServiceShortcuts").listShortcutServiceShortcuts = null as any;
export const listShortcutServiceShortcutsOutput: typeof import("./listShortcutServiceShortcuts").listShortcutServiceShortcutsOutput = null as any;
utilities.lazyLoad(exports, ["listShortcutServiceShortcuts","listShortcutServiceShortcutsOutput"], () => require("./listShortcutServiceShortcuts"));

export { ShortcutServiceShortcutArgs } from "./shortcutServiceShortcut";
export type ShortcutServiceShortcut = import("./shortcutServiceShortcut").ShortcutServiceShortcut;
export const ShortcutServiceShortcut: typeof import("./shortcutServiceShortcut").ShortcutServiceShortcut = null as any;
utilities.lazyLoad(exports, ["ShortcutServiceShortcut"], () => require("./shortcutServiceShortcut"));


// Export enums:
export * from "../types/enums/api";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "slash:api:ShortcutServiceShortcut":
                return new ShortcutServiceShortcut(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("slash", "api", _module)
