// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listUserServiceUsers(args?: ListUserServiceUsersArgs, opts?: pulumi.InvokeOptions): Promise<ListUserServiceUsersResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:listUserServiceUsers", {
    }, opts);
}

export interface ListUserServiceUsersArgs {
}

export interface ListUserServiceUsersResult {
    readonly items: outputs.api.V1ListUsersResponse;
}
export function listUserServiceUsersOutput(opts?: pulumi.InvokeOptions): pulumi.Output<ListUserServiceUsersResult> {
    return pulumi.output(listUserServiceUsers(opts))
}
