// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listCollectionServiceCollections(args?: ListCollectionServiceCollectionsArgs, opts?: pulumi.InvokeOptions): Promise<ListCollectionServiceCollectionsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:listCollectionServiceCollections", {
    }, opts);
}

export interface ListCollectionServiceCollectionsArgs {
}

export interface ListCollectionServiceCollectionsResult {
    readonly items: outputs.api.V1ListCollectionsResponse;
}
export function listCollectionServiceCollectionsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<ListCollectionServiceCollectionsResult> {
    return pulumi.output(listCollectionServiceCollections(opts))
}
