// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listShortcutServiceShortcuts(args?: ListShortcutServiceShortcutsArgs, opts?: pulumi.InvokeOptions): Promise<ListShortcutServiceShortcutsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("slash:api:listShortcutServiceShortcuts", {
    }, opts);
}

export interface ListShortcutServiceShortcutsArgs {
}

export interface ListShortcutServiceShortcutsResult {
    readonly items: outputs.api.V1ListShortcutsResponse;
}
export function listShortcutServiceShortcutsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<ListShortcutServiceShortcutsResult> {
    return pulumi.output(listShortcutServiceShortcuts(opts))
}
