// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class UserServiceUserAccessToken extends pulumi.CustomResource {
    /**
     * Get an existing UserServiceUserAccessToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): UserServiceUserAccessToken {
        return new UserServiceUserAccessToken(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'slash:api:UserServiceUserAccessToken';

    /**
     * Returns true if the given object is an instance of UserServiceUserAccessToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserServiceUserAccessToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserServiceUserAccessToken.__pulumiType;
    }

    public /*out*/ readonly accessToken!: pulumi.Output<outputs.api.V1UserAccessToken | undefined>;
    /**
     * description is the description of the access token.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * expires_at is the expiration time of the access token.
     * If expires_at is not set, the access token will never expire.
     */
    public readonly expiresAt!: pulumi.Output<string | undefined>;

    /**
     * Create a UserServiceUserAccessToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: UserServiceUserAccessTokenArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["expiresAt"] = args ? args.expiresAt : undefined;
            resourceInputs["id"] = args ? args.id : undefined;
            resourceInputs["accessToken"] = undefined /*out*/;
        } else {
            resourceInputs["accessToken"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UserServiceUserAccessToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a UserServiceUserAccessToken resource.
 */
export interface UserServiceUserAccessTokenArgs {
    /**
     * description is the description of the access token.
     */
    description?: pulumi.Input<string>;
    /**
     * expires_at is the expiration time of the access token.
     * If expires_at is not set, the access token will never expire.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * id is the user id.
     */
    id?: pulumi.Input<string>;
}
