// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupShortcutServiceShortcut(ctx *pulumi.Context, args *LookupShortcutServiceShortcutArgs, opts ...pulumi.InvokeOption) (*LookupShortcutServiceShortcutResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupShortcutServiceShortcutResult
	err := ctx.Invoke("slash:api:getShortcutServiceShortcut", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type LookupShortcutServiceShortcutArgs struct {
	Id string `pulumi:"id"`
}

type LookupShortcutServiceShortcutResult struct {
	Items V1GetShortcutResponse `pulumi:"items"`
}

// Defaults sets the appropriate defaults for LookupShortcutServiceShortcutResult
func (val *LookupShortcutServiceShortcutResult) Defaults() *LookupShortcutServiceShortcutResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Items = *tmp.Items.Defaults()

	return &tmp
}

func LookupShortcutServiceShortcutOutput(ctx *pulumi.Context, args LookupShortcutServiceShortcutOutputArgs, opts ...pulumi.InvokeOption) LookupShortcutServiceShortcutResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupShortcutServiceShortcutResult, error) {
			args := v.(LookupShortcutServiceShortcutArgs)
			r, err := LookupShortcutServiceShortcut(ctx, &args, opts...)
			var s LookupShortcutServiceShortcutResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupShortcutServiceShortcutResultOutput)
}

type LookupShortcutServiceShortcutOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupShortcutServiceShortcutOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupShortcutServiceShortcutArgs)(nil)).Elem()
}

type LookupShortcutServiceShortcutResultOutput struct{ *pulumi.OutputState }

func (LookupShortcutServiceShortcutResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupShortcutServiceShortcutResult)(nil)).Elem()
}

func (o LookupShortcutServiceShortcutResultOutput) ToLookupShortcutServiceShortcutResultOutput() LookupShortcutServiceShortcutResultOutput {
	return o
}

func (o LookupShortcutServiceShortcutResultOutput) ToLookupShortcutServiceShortcutResultOutputWithContext(ctx context.Context) LookupShortcutServiceShortcutResultOutput {
	return o
}

func (o LookupShortcutServiceShortcutResultOutput) Items() V1GetShortcutResponseOutput {
	return o.ApplyT(func(v LookupShortcutServiceShortcutResult) V1GetShortcutResponse { return v.Items }).(V1GetShortcutResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupShortcutServiceShortcutResultOutput{})
}
