// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetUserSettingServiceUserSetting(ctx *pulumi.Context, args *GetUserSettingServiceUserSettingArgs, opts ...pulumi.InvokeOption) (*GetUserSettingServiceUserSettingResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetUserSettingServiceUserSettingResult
	err := ctx.Invoke("slash:api:getUserSettingServiceUserSetting", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type GetUserSettingServiceUserSettingArgs struct {
	// id is the user id.
	Id string `pulumi:"id"`
}

type GetUserSettingServiceUserSettingResult struct {
	Items V1GetUserSettingResponse `pulumi:"items"`
}

// Defaults sets the appropriate defaults for GetUserSettingServiceUserSettingResult
func (val *GetUserSettingServiceUserSettingResult) Defaults() *GetUserSettingServiceUserSettingResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Items = *tmp.Items.Defaults()

	return &tmp
}

func GetUserSettingServiceUserSettingOutput(ctx *pulumi.Context, args GetUserSettingServiceUserSettingOutputArgs, opts ...pulumi.InvokeOption) GetUserSettingServiceUserSettingResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetUserSettingServiceUserSettingResult, error) {
			args := v.(GetUserSettingServiceUserSettingArgs)
			r, err := GetUserSettingServiceUserSetting(ctx, &args, opts...)
			var s GetUserSettingServiceUserSettingResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetUserSettingServiceUserSettingResultOutput)
}

type GetUserSettingServiceUserSettingOutputArgs struct {
	// id is the user id.
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetUserSettingServiceUserSettingOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserSettingServiceUserSettingArgs)(nil)).Elem()
}

type GetUserSettingServiceUserSettingResultOutput struct{ *pulumi.OutputState }

func (GetUserSettingServiceUserSettingResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserSettingServiceUserSettingResult)(nil)).Elem()
}

func (o GetUserSettingServiceUserSettingResultOutput) ToGetUserSettingServiceUserSettingResultOutput() GetUserSettingServiceUserSettingResultOutput {
	return o
}

func (o GetUserSettingServiceUserSettingResultOutput) ToGetUserSettingServiceUserSettingResultOutputWithContext(ctx context.Context) GetUserSettingServiceUserSettingResultOutput {
	return o
}

func (o GetUserSettingServiceUserSettingResultOutput) Items() V1GetUserSettingResponseOutput {
	return o.ApplyT(func(v GetUserSettingServiceUserSettingResult) V1GetUserSettingResponse { return v.Items }).(V1GetUserSettingResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUserSettingServiceUserSettingResultOutput{})
}
