// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetWorkspaceServiceWorkspaceSetting(ctx *pulumi.Context, args *GetWorkspaceServiceWorkspaceSettingArgs, opts ...pulumi.InvokeOption) (*GetWorkspaceServiceWorkspaceSettingResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetWorkspaceServiceWorkspaceSettingResult
	err := ctx.Invoke("slash:api:getWorkspaceServiceWorkspaceSetting", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type GetWorkspaceServiceWorkspaceSettingArgs struct {
}

type GetWorkspaceServiceWorkspaceSettingResult struct {
	Items V1GetWorkspaceSettingResponse `pulumi:"items"`
}

// Defaults sets the appropriate defaults for GetWorkspaceServiceWorkspaceSettingResult
func (val *GetWorkspaceServiceWorkspaceSettingResult) Defaults() *GetWorkspaceServiceWorkspaceSettingResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Items = *tmp.Items.Defaults()

	return &tmp
}

func GetWorkspaceServiceWorkspaceSettingOutput(ctx *pulumi.Context, args GetWorkspaceServiceWorkspaceSettingOutputArgs, opts ...pulumi.InvokeOption) GetWorkspaceServiceWorkspaceSettingResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetWorkspaceServiceWorkspaceSettingResult, error) {
			args := v.(GetWorkspaceServiceWorkspaceSettingArgs)
			r, err := GetWorkspaceServiceWorkspaceSetting(ctx, &args, opts...)
			var s GetWorkspaceServiceWorkspaceSettingResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetWorkspaceServiceWorkspaceSettingResultOutput)
}

type GetWorkspaceServiceWorkspaceSettingOutputArgs struct {
}

func (GetWorkspaceServiceWorkspaceSettingOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkspaceServiceWorkspaceSettingArgs)(nil)).Elem()
}

type GetWorkspaceServiceWorkspaceSettingResultOutput struct{ *pulumi.OutputState }

func (GetWorkspaceServiceWorkspaceSettingResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkspaceServiceWorkspaceSettingResult)(nil)).Elem()
}

func (o GetWorkspaceServiceWorkspaceSettingResultOutput) ToGetWorkspaceServiceWorkspaceSettingResultOutput() GetWorkspaceServiceWorkspaceSettingResultOutput {
	return o
}

func (o GetWorkspaceServiceWorkspaceSettingResultOutput) ToGetWorkspaceServiceWorkspaceSettingResultOutputWithContext(ctx context.Context) GetWorkspaceServiceWorkspaceSettingResultOutput {
	return o
}

func (o GetWorkspaceServiceWorkspaceSettingResultOutput) Items() V1GetWorkspaceSettingResponseOutput {
	return o.ApplyT(func(v GetWorkspaceServiceWorkspaceSettingResult) V1GetWorkspaceSettingResponse { return v.Items }).(V1GetWorkspaceSettingResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(GetWorkspaceServiceWorkspaceSettingResultOutput{})
}
