// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetWorkspaceServiceWorkspaceProfile(ctx *pulumi.Context, args *GetWorkspaceServiceWorkspaceProfileArgs, opts ...pulumi.InvokeOption) (*GetWorkspaceServiceWorkspaceProfileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetWorkspaceServiceWorkspaceProfileResult
	err := ctx.Invoke("slash:api:getWorkspaceServiceWorkspaceProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type GetWorkspaceServiceWorkspaceProfileArgs struct {
}

type GetWorkspaceServiceWorkspaceProfileResult struct {
	Items V1GetWorkspaceProfileResponse `pulumi:"items"`
}

// Defaults sets the appropriate defaults for GetWorkspaceServiceWorkspaceProfileResult
func (val *GetWorkspaceServiceWorkspaceProfileResult) Defaults() *GetWorkspaceServiceWorkspaceProfileResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Items = *tmp.Items.Defaults()

	return &tmp
}

func GetWorkspaceServiceWorkspaceProfileOutput(ctx *pulumi.Context, args GetWorkspaceServiceWorkspaceProfileOutputArgs, opts ...pulumi.InvokeOption) GetWorkspaceServiceWorkspaceProfileResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetWorkspaceServiceWorkspaceProfileResult, error) {
			args := v.(GetWorkspaceServiceWorkspaceProfileArgs)
			r, err := GetWorkspaceServiceWorkspaceProfile(ctx, &args, opts...)
			var s GetWorkspaceServiceWorkspaceProfileResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetWorkspaceServiceWorkspaceProfileResultOutput)
}

type GetWorkspaceServiceWorkspaceProfileOutputArgs struct {
}

func (GetWorkspaceServiceWorkspaceProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkspaceServiceWorkspaceProfileArgs)(nil)).Elem()
}

type GetWorkspaceServiceWorkspaceProfileResultOutput struct{ *pulumi.OutputState }

func (GetWorkspaceServiceWorkspaceProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkspaceServiceWorkspaceProfileResult)(nil)).Elem()
}

func (o GetWorkspaceServiceWorkspaceProfileResultOutput) ToGetWorkspaceServiceWorkspaceProfileResultOutput() GetWorkspaceServiceWorkspaceProfileResultOutput {
	return o
}

func (o GetWorkspaceServiceWorkspaceProfileResultOutput) ToGetWorkspaceServiceWorkspaceProfileResultOutputWithContext(ctx context.Context) GetWorkspaceServiceWorkspaceProfileResultOutput {
	return o
}

func (o GetWorkspaceServiceWorkspaceProfileResultOutput) Items() V1GetWorkspaceProfileResponseOutput {
	return o.ApplyT(func(v GetWorkspaceServiceWorkspaceProfileResult) V1GetWorkspaceProfileResponse { return v.Items }).(V1GetWorkspaceProfileResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(GetWorkspaceServiceWorkspaceProfileResultOutput{})
}
