// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListShortcutServiceShortcuts(ctx *pulumi.Context, args *ListShortcutServiceShortcutsArgs, opts ...pulumi.InvokeOption) (*ListShortcutServiceShortcutsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListShortcutServiceShortcutsResult
	err := ctx.Invoke("slash:api:listShortcutServiceShortcuts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListShortcutServiceShortcutsArgs struct {
}

type ListShortcutServiceShortcutsResult struct {
	Items V1ListShortcutsResponse `pulumi:"items"`
}

func ListShortcutServiceShortcutsOutput(ctx *pulumi.Context, args ListShortcutServiceShortcutsOutputArgs, opts ...pulumi.InvokeOption) ListShortcutServiceShortcutsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListShortcutServiceShortcutsResult, error) {
			args := v.(ListShortcutServiceShortcutsArgs)
			r, err := ListShortcutServiceShortcuts(ctx, &args, opts...)
			var s ListShortcutServiceShortcutsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ListShortcutServiceShortcutsResultOutput)
}

type ListShortcutServiceShortcutsOutputArgs struct {
}

func (ListShortcutServiceShortcutsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListShortcutServiceShortcutsArgs)(nil)).Elem()
}

type ListShortcutServiceShortcutsResultOutput struct{ *pulumi.OutputState }

func (ListShortcutServiceShortcutsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListShortcutServiceShortcutsResult)(nil)).Elem()
}

func (o ListShortcutServiceShortcutsResultOutput) ToListShortcutServiceShortcutsResultOutput() ListShortcutServiceShortcutsResultOutput {
	return o
}

func (o ListShortcutServiceShortcutsResultOutput) ToListShortcutServiceShortcutsResultOutputWithContext(ctx context.Context) ListShortcutServiceShortcutsResultOutput {
	return o
}

func (o ListShortcutServiceShortcutsResultOutput) Items() V1ListShortcutsResponseOutput {
	return o.ApplyT(func(v ListShortcutServiceShortcutsResult) V1ListShortcutsResponse { return v.Items }).(V1ListShortcutsResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(ListShortcutServiceShortcutsResultOutput{})
}
