// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListUserServiceUserAccessTokens(ctx *pulumi.Context, args *ListUserServiceUserAccessTokensArgs, opts ...pulumi.InvokeOption) (*ListUserServiceUserAccessTokensResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListUserServiceUserAccessTokensResult
	err := ctx.Invoke("slash:api:listUserServiceUserAccessTokens", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListUserServiceUserAccessTokensArgs struct {
	// id is the user id.
	Id string `pulumi:"id"`
}

type ListUserServiceUserAccessTokensResult struct {
	Items V1ListUserAccessTokensResponse `pulumi:"items"`
}

func ListUserServiceUserAccessTokensOutput(ctx *pulumi.Context, args ListUserServiceUserAccessTokensOutputArgs, opts ...pulumi.InvokeOption) ListUserServiceUserAccessTokensResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListUserServiceUserAccessTokensResult, error) {
			args := v.(ListUserServiceUserAccessTokensArgs)
			r, err := ListUserServiceUserAccessTokens(ctx, &args, opts...)
			var s ListUserServiceUserAccessTokensResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ListUserServiceUserAccessTokensResultOutput)
}

type ListUserServiceUserAccessTokensOutputArgs struct {
	// id is the user id.
	Id pulumi.StringInput `pulumi:"id"`
}

func (ListUserServiceUserAccessTokensOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListUserServiceUserAccessTokensArgs)(nil)).Elem()
}

type ListUserServiceUserAccessTokensResultOutput struct{ *pulumi.OutputState }

func (ListUserServiceUserAccessTokensResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListUserServiceUserAccessTokensResult)(nil)).Elem()
}

func (o ListUserServiceUserAccessTokensResultOutput) ToListUserServiceUserAccessTokensResultOutput() ListUserServiceUserAccessTokensResultOutput {
	return o
}

func (o ListUserServiceUserAccessTokensResultOutput) ToListUserServiceUserAccessTokensResultOutputWithContext(ctx context.Context) ListUserServiceUserAccessTokensResultOutput {
	return o
}

func (o ListUserServiceUserAccessTokensResultOutput) Items() V1ListUserAccessTokensResponseOutput {
	return o.ApplyT(func(v ListUserServiceUserAccessTokensResult) V1ListUserAccessTokensResponse { return v.Items }).(V1ListUserAccessTokensResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(ListUserServiceUserAccessTokensResultOutput{})
}
