// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Apiv1ShortcutRowStatus string

const (
	Apiv1ShortcutRowStatusRowStatusUnspecified = Apiv1ShortcutRowStatus("ROW_STATUS_UNSPECIFIED")
	Apiv1ShortcutRowStatusNormal               = Apiv1ShortcutRowStatus("NORMAL")
	Apiv1ShortcutRowStatusArchived             = Apiv1ShortcutRowStatus("ARCHIVED")
)

type Apiv1ShortcutRowStatusOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutRowStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1ShortcutRowStatus)(nil)).Elem()
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusOutput() Apiv1ShortcutRowStatusOutput {
	return o
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusOutputWithContext(ctx context.Context) Apiv1ShortcutRowStatusOutput {
	return o
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusPtrOutput() Apiv1ShortcutRowStatusPtrOutput {
	return o.ToApiv1ShortcutRowStatusPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusPtrOutputWithContext(ctx context.Context) Apiv1ShortcutRowStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1ShortcutRowStatus) *Apiv1ShortcutRowStatus {
		return &v
	}).(Apiv1ShortcutRowStatusPtrOutput)
}

func (o Apiv1ShortcutRowStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutRowStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1ShortcutRowStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutRowStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutRowStatusPtrOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutRowStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1ShortcutRowStatus)(nil)).Elem()
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToApiv1ShortcutRowStatusPtrOutput() Apiv1ShortcutRowStatusPtrOutput {
	return o
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToApiv1ShortcutRowStatusPtrOutputWithContext(ctx context.Context) Apiv1ShortcutRowStatusPtrOutput {
	return o
}

func (o Apiv1ShortcutRowStatusPtrOutput) Elem() Apiv1ShortcutRowStatusOutput {
	return o.ApplyT(func(v *Apiv1ShortcutRowStatus) Apiv1ShortcutRowStatus {
		if v != nil {
			return *v
		}
		var ret Apiv1ShortcutRowStatus
		return ret
	}).(Apiv1ShortcutRowStatusOutput)
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1ShortcutRowStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutVisibility string

const (
	Apiv1ShortcutVisibilityVisibilityUnspecified = Apiv1ShortcutVisibility("VISIBILITY_UNSPECIFIED")
	Apiv1ShortcutVisibilityPrivate               = Apiv1ShortcutVisibility("PRIVATE")
	Apiv1ShortcutVisibilityWorkspace             = Apiv1ShortcutVisibility("WORKSPACE")
	Apiv1ShortcutVisibilityPublic                = Apiv1ShortcutVisibility("PUBLIC")
)

type Apiv1ShortcutVisibilityOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutVisibilityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1ShortcutVisibility)(nil)).Elem()
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityOutput() Apiv1ShortcutVisibilityOutput {
	return o
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityOutputWithContext(ctx context.Context) Apiv1ShortcutVisibilityOutput {
	return o
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityPtrOutput() Apiv1ShortcutVisibilityPtrOutput {
	return o.ToApiv1ShortcutVisibilityPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityPtrOutputWithContext(ctx context.Context) Apiv1ShortcutVisibilityPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1ShortcutVisibility) *Apiv1ShortcutVisibility {
		return &v
	}).(Apiv1ShortcutVisibilityPtrOutput)
}

func (o Apiv1ShortcutVisibilityOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutVisibility) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1ShortcutVisibilityOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutVisibility) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutVisibilityPtrOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutVisibilityPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1ShortcutVisibility)(nil)).Elem()
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToApiv1ShortcutVisibilityPtrOutput() Apiv1ShortcutVisibilityPtrOutput {
	return o
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToApiv1ShortcutVisibilityPtrOutputWithContext(ctx context.Context) Apiv1ShortcutVisibilityPtrOutput {
	return o
}

func (o Apiv1ShortcutVisibilityPtrOutput) Elem() Apiv1ShortcutVisibilityOutput {
	return o.ApplyT(func(v *Apiv1ShortcutVisibility) Apiv1ShortcutVisibility {
		if v != nil {
			return *v
		}
		var ret Apiv1ShortcutVisibility
		return ret
	}).(Apiv1ShortcutVisibilityOutput)
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1ShortcutVisibility) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RowStatus string

const (
	RowStatusRowStatusUnspecified = RowStatus("ROW_STATUS_UNSPECIFIED")
	RowStatusNormal               = RowStatus("NORMAL")
	RowStatusArchived             = RowStatus("ARCHIVED")
)

func (RowStatus) ElementType() reflect.Type {
	return reflect.TypeOf((*RowStatus)(nil)).Elem()
}

func (e RowStatus) ToRowStatusOutput() RowStatusOutput {
	return pulumi.ToOutput(e).(RowStatusOutput)
}

func (e RowStatus) ToRowStatusOutputWithContext(ctx context.Context) RowStatusOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RowStatusOutput)
}

func (e RowStatus) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return e.ToRowStatusPtrOutputWithContext(context.Background())
}

func (e RowStatus) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return RowStatus(e).ToRowStatusOutputWithContext(ctx).ToRowStatusPtrOutputWithContext(ctx)
}

func (e RowStatus) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e RowStatus) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e RowStatus) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e RowStatus) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RowStatusOutput struct{ *pulumi.OutputState }

func (RowStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RowStatus)(nil)).Elem()
}

func (o RowStatusOutput) ToRowStatusOutput() RowStatusOutput {
	return o
}

func (o RowStatusOutput) ToRowStatusOutputWithContext(ctx context.Context) RowStatusOutput {
	return o
}

func (o RowStatusOutput) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return o.ToRowStatusPtrOutputWithContext(context.Background())
}

func (o RowStatusOutput) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RowStatus) *RowStatus {
		return &v
	}).(RowStatusPtrOutput)
}

func (o RowStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RowStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RowStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RowStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RowStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RowStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RowStatusPtrOutput struct{ *pulumi.OutputState }

func (RowStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RowStatus)(nil)).Elem()
}

func (o RowStatusPtrOutput) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return o
}

func (o RowStatusPtrOutput) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return o
}

func (o RowStatusPtrOutput) Elem() RowStatusOutput {
	return o.ApplyT(func(v *RowStatus) RowStatus {
		if v != nil {
			return *v
		}
		var ret RowStatus
		return ret
	}).(RowStatusOutput)
}

func (o RowStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RowStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RowStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RowStatusInput is an input type that accepts values of the RowStatus enum
// A concrete instance of `RowStatusInput` can be one of the following:
//
//	RowStatusRowStatusUnspecified
//	RowStatusNormal
//	RowStatusArchived
type RowStatusInput interface {
	pulumi.Input

	ToRowStatusOutput() RowStatusOutput
	ToRowStatusOutputWithContext(context.Context) RowStatusOutput
}

var rowStatusPtrType = reflect.TypeOf((**RowStatus)(nil)).Elem()

type RowStatusPtrInput interface {
	pulumi.Input

	ToRowStatusPtrOutput() RowStatusPtrOutput
	ToRowStatusPtrOutputWithContext(context.Context) RowStatusPtrOutput
}

type rowStatusPtr string

func RowStatusPtr(v string) RowStatusPtrInput {
	return (*rowStatusPtr)(&v)
}

func (*rowStatusPtr) ElementType() reflect.Type {
	return rowStatusPtrType
}

func (in *rowStatusPtr) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return pulumi.ToOutput(in).(RowStatusPtrOutput)
}

func (in *rowStatusPtr) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RowStatusPtrOutput)
}

type Visibility string

const (
	VisibilityVisibilityUnspecified = Visibility("VISIBILITY_UNSPECIFIED")
	VisibilityPrivate               = Visibility("PRIVATE")
	VisibilityWorkspace             = Visibility("WORKSPACE")
	VisibilityPublic                = Visibility("PUBLIC")
)

func (Visibility) ElementType() reflect.Type {
	return reflect.TypeOf((*Visibility)(nil)).Elem()
}

func (e Visibility) ToVisibilityOutput() VisibilityOutput {
	return pulumi.ToOutput(e).(VisibilityOutput)
}

func (e Visibility) ToVisibilityOutputWithContext(ctx context.Context) VisibilityOutput {
	return pulumi.ToOutputWithContext(ctx, e).(VisibilityOutput)
}

func (e Visibility) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return e.ToVisibilityPtrOutputWithContext(context.Background())
}

func (e Visibility) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return Visibility(e).ToVisibilityOutputWithContext(ctx).ToVisibilityPtrOutputWithContext(ctx)
}

func (e Visibility) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e Visibility) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e Visibility) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e Visibility) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type VisibilityOutput struct{ *pulumi.OutputState }

func (VisibilityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Visibility)(nil)).Elem()
}

func (o VisibilityOutput) ToVisibilityOutput() VisibilityOutput {
	return o
}

func (o VisibilityOutput) ToVisibilityOutputWithContext(ctx context.Context) VisibilityOutput {
	return o
}

func (o VisibilityOutput) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return o.ToVisibilityPtrOutputWithContext(context.Background())
}

func (o VisibilityOutput) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Visibility) *Visibility {
		return &v
	}).(VisibilityPtrOutput)
}

func (o VisibilityOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o VisibilityOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Visibility) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o VisibilityOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o VisibilityOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Visibility) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type VisibilityPtrOutput struct{ *pulumi.OutputState }

func (VisibilityPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Visibility)(nil)).Elem()
}

func (o VisibilityPtrOutput) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return o
}

func (o VisibilityPtrOutput) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return o
}

func (o VisibilityPtrOutput) Elem() VisibilityOutput {
	return o.ApplyT(func(v *Visibility) Visibility {
		if v != nil {
			return *v
		}
		var ret Visibility
		return ret
	}).(VisibilityOutput)
}

func (o VisibilityPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o VisibilityPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Visibility) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// VisibilityInput is an input type that accepts values of the Visibility enum
// A concrete instance of `VisibilityInput` can be one of the following:
//
//	VisibilityVisibilityUnspecified
//	VisibilityPrivate
//	VisibilityWorkspace
//	VisibilityPublic
type VisibilityInput interface {
	pulumi.Input

	ToVisibilityOutput() VisibilityOutput
	ToVisibilityOutputWithContext(context.Context) VisibilityOutput
}

var visibilityPtrType = reflect.TypeOf((**Visibility)(nil)).Elem()

type VisibilityPtrInput interface {
	pulumi.Input

	ToVisibilityPtrOutput() VisibilityPtrOutput
	ToVisibilityPtrOutputWithContext(context.Context) VisibilityPtrOutput
}

type visibilityPtr string

func VisibilityPtr(v string) VisibilityPtrInput {
	return (*visibilityPtr)(&v)
}

func (*visibilityPtr) ElementType() reflect.Type {
	return visibilityPtrType
}

func (in *visibilityPtr) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return pulumi.ToOutput(in).(VisibilityPtrOutput)
}

func (in *visibilityPtr) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(VisibilityPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RowStatusInput)(nil)).Elem(), RowStatus("ROW_STATUS_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*RowStatusPtrInput)(nil)).Elem(), RowStatus("ROW_STATUS_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*VisibilityInput)(nil)).Elem(), Visibility("VISIBILITY_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*VisibilityPtrInput)(nil)).Elem(), Visibility("VISIBILITY_UNSPECIFIED"))
	pulumi.RegisterOutputType(Apiv1ShortcutRowStatusOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutRowStatusPtrOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutVisibilityOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutVisibilityPtrOutput{})
	pulumi.RegisterOutputType(RowStatusOutput{})
	pulumi.RegisterOutputType(RowStatusPtrOutput{})
	pulumi.RegisterOutputType(VisibilityOutput{})
	pulumi.RegisterOutputType(VisibilityPtrOutput{})
}
