// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/dddd4cloud/pulumi-provider-slash/sdk/go/slash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Apiv1AutoBackupWorkspaceSetting struct {
	// The cron expression for auto backup.
	// For example, "0 0 0 * * *" means backup at 00:00:00 every day.
	// See https://en.wikipedia.org/wiki/Cron for more details.
	CronExpression *string `pulumi:"cronExpression"`
	// Whether auto backup is enabled.
	Enabled *bool `pulumi:"enabled"`
	// The maximum number of backups to keep.
	MaxKeep *int `pulumi:"maxKeep"`
}

type Apiv1AutoBackupWorkspaceSettingOutput struct{ *pulumi.OutputState }

func (Apiv1AutoBackupWorkspaceSettingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1AutoBackupWorkspaceSetting)(nil)).Elem()
}

func (o Apiv1AutoBackupWorkspaceSettingOutput) ToApiv1AutoBackupWorkspaceSettingOutput() Apiv1AutoBackupWorkspaceSettingOutput {
	return o
}

func (o Apiv1AutoBackupWorkspaceSettingOutput) ToApiv1AutoBackupWorkspaceSettingOutputWithContext(ctx context.Context) Apiv1AutoBackupWorkspaceSettingOutput {
	return o
}

// The cron expression for auto backup.
// For example, "0 0 0 * * *" means backup at 00:00:00 every day.
// See https://en.wikipedia.org/wiki/Cron for more details.
func (o Apiv1AutoBackupWorkspaceSettingOutput) CronExpression() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1AutoBackupWorkspaceSetting) *string { return v.CronExpression }).(pulumi.StringPtrOutput)
}

// Whether auto backup is enabled.
func (o Apiv1AutoBackupWorkspaceSettingOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Apiv1AutoBackupWorkspaceSetting) *bool { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// The maximum number of backups to keep.
func (o Apiv1AutoBackupWorkspaceSettingOutput) MaxKeep() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1AutoBackupWorkspaceSetting) *int { return v.MaxKeep }).(pulumi.IntPtrOutput)
}

type Apiv1AutoBackupWorkspaceSettingPtrOutput struct{ *pulumi.OutputState }

func (Apiv1AutoBackupWorkspaceSettingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1AutoBackupWorkspaceSetting)(nil)).Elem()
}

func (o Apiv1AutoBackupWorkspaceSettingPtrOutput) ToApiv1AutoBackupWorkspaceSettingPtrOutput() Apiv1AutoBackupWorkspaceSettingPtrOutput {
	return o
}

func (o Apiv1AutoBackupWorkspaceSettingPtrOutput) ToApiv1AutoBackupWorkspaceSettingPtrOutputWithContext(ctx context.Context) Apiv1AutoBackupWorkspaceSettingPtrOutput {
	return o
}

func (o Apiv1AutoBackupWorkspaceSettingPtrOutput) Elem() Apiv1AutoBackupWorkspaceSettingOutput {
	return o.ApplyT(func(v *Apiv1AutoBackupWorkspaceSetting) Apiv1AutoBackupWorkspaceSetting {
		if v != nil {
			return *v
		}
		var ret Apiv1AutoBackupWorkspaceSetting
		return ret
	}).(Apiv1AutoBackupWorkspaceSettingOutput)
}

// The cron expression for auto backup.
// For example, "0 0 0 * * *" means backup at 00:00:00 every day.
// See https://en.wikipedia.org/wiki/Cron for more details.
func (o Apiv1AutoBackupWorkspaceSettingPtrOutput) CronExpression() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1AutoBackupWorkspaceSetting) *string {
		if v == nil {
			return nil
		}
		return v.CronExpression
	}).(pulumi.StringPtrOutput)
}

// Whether auto backup is enabled.
func (o Apiv1AutoBackupWorkspaceSettingPtrOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Apiv1AutoBackupWorkspaceSetting) *bool {
		if v == nil {
			return nil
		}
		return v.Enabled
	}).(pulumi.BoolPtrOutput)
}

// The maximum number of backups to keep.
func (o Apiv1AutoBackupWorkspaceSettingPtrOutput) MaxKeep() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1AutoBackupWorkspaceSetting) *int {
		if v == nil {
			return nil
		}
		return v.MaxKeep
	}).(pulumi.IntPtrOutput)
}

type Apiv1Collection struct {
	CreatedTime *string                    `pulumi:"createdTime"`
	CreatorId   *int                       `pulumi:"creatorId"`
	Description *string                    `pulumi:"description"`
	Id          *int                       `pulumi:"id"`
	Name        *string                    `pulumi:"name"`
	ShortcutIds []int                      `pulumi:"shortcutIds"`
	Title       *string                    `pulumi:"title"`
	UpdatedTime *string                    `pulumi:"updatedTime"`
	Visibility  *Apiv1CollectionVisibility `pulumi:"visibility"`
}

// Defaults sets the appropriate defaults for Apiv1Collection
func (val *Apiv1Collection) Defaults() *Apiv1Collection {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Visibility == nil {
		visibility_ := Apiv1CollectionVisibility("VISIBILITY_UNSPECIFIED")
		tmp.Visibility = &visibility_
	}
	return &tmp
}

type Apiv1CollectionOutput struct{ *pulumi.OutputState }

func (Apiv1CollectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1Collection)(nil)).Elem()
}

func (o Apiv1CollectionOutput) ToApiv1CollectionOutput() Apiv1CollectionOutput {
	return o
}

func (o Apiv1CollectionOutput) ToApiv1CollectionOutputWithContext(ctx context.Context) Apiv1CollectionOutput {
	return o
}

func (o Apiv1CollectionOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *string { return v.CreatedTime }).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionOutput) CreatorId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *int { return v.CreatorId }).(pulumi.IntPtrOutput)
}

func (o Apiv1CollectionOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o Apiv1CollectionOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionOutput) ShortcutIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v Apiv1Collection) []int { return v.ShortcutIds }).(pulumi.IntArrayOutput)
}

func (o Apiv1CollectionOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *string { return v.Title }).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionOutput) UpdatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *string { return v.UpdatedTime }).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionOutput) Visibility() Apiv1CollectionVisibilityPtrOutput {
	return o.ApplyT(func(v Apiv1Collection) *Apiv1CollectionVisibility { return v.Visibility }).(Apiv1CollectionVisibilityPtrOutput)
}

type Apiv1CollectionPtrOutput struct{ *pulumi.OutputState }

func (Apiv1CollectionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1Collection)(nil)).Elem()
}

func (o Apiv1CollectionPtrOutput) ToApiv1CollectionPtrOutput() Apiv1CollectionPtrOutput {
	return o
}

func (o Apiv1CollectionPtrOutput) ToApiv1CollectionPtrOutputWithContext(ctx context.Context) Apiv1CollectionPtrOutput {
	return o
}

func (o Apiv1CollectionPtrOutput) Elem() Apiv1CollectionOutput {
	return o.ApplyT(func(v *Apiv1Collection) Apiv1Collection {
		if v != nil {
			return *v
		}
		var ret Apiv1Collection
		return ret
	}).(Apiv1CollectionOutput)
}

func (o Apiv1CollectionPtrOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *string {
		if v == nil {
			return nil
		}
		return v.CreatedTime
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionPtrOutput) CreatorId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *int {
		if v == nil {
			return nil
		}
		return v.CreatorId
	}).(pulumi.IntPtrOutput)
}

func (o Apiv1CollectionPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *string {
		if v == nil {
			return nil
		}
		return v.Description
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionPtrOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *int {
		if v == nil {
			return nil
		}
		return v.Id
	}).(pulumi.IntPtrOutput)
}

func (o Apiv1CollectionPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *string {
		if v == nil {
			return nil
		}
		return v.Name
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionPtrOutput) ShortcutIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Apiv1Collection) []int {
		if v == nil {
			return nil
		}
		return v.ShortcutIds
	}).(pulumi.IntArrayOutput)
}

func (o Apiv1CollectionPtrOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *string {
		if v == nil {
			return nil
		}
		return v.Title
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionPtrOutput) UpdatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *string {
		if v == nil {
			return nil
		}
		return v.UpdatedTime
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1CollectionPtrOutput) Visibility() Apiv1CollectionVisibilityPtrOutput {
	return o.ApplyT(func(v *Apiv1Collection) *Apiv1CollectionVisibility {
		if v == nil {
			return nil
		}
		return v.Visibility
	}).(Apiv1CollectionVisibilityPtrOutput)
}

type Apiv1CollectionArrayOutput struct{ *pulumi.OutputState }

func (Apiv1CollectionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Apiv1Collection)(nil)).Elem()
}

func (o Apiv1CollectionArrayOutput) ToApiv1CollectionArrayOutput() Apiv1CollectionArrayOutput {
	return o
}

func (o Apiv1CollectionArrayOutput) ToApiv1CollectionArrayOutputWithContext(ctx context.Context) Apiv1CollectionArrayOutput {
	return o
}

func (o Apiv1CollectionArrayOutput) Index(i pulumi.IntInput) Apiv1CollectionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Apiv1Collection {
		return vs[0].([]Apiv1Collection)[vs[1].(int)]
	}).(Apiv1CollectionOutput)
}

type Apiv1OpenGraphMetadata struct {
	Description *string `pulumi:"description"`
	Image       *string `pulumi:"image"`
	Title       *string `pulumi:"title"`
}

// Apiv1OpenGraphMetadataInput is an input type that accepts Apiv1OpenGraphMetadataArgs and Apiv1OpenGraphMetadataOutput values.
// You can construct a concrete instance of `Apiv1OpenGraphMetadataInput` via:
//
//	Apiv1OpenGraphMetadataArgs{...}
type Apiv1OpenGraphMetadataInput interface {
	pulumi.Input

	ToApiv1OpenGraphMetadataOutput() Apiv1OpenGraphMetadataOutput
	ToApiv1OpenGraphMetadataOutputWithContext(context.Context) Apiv1OpenGraphMetadataOutput
}

type Apiv1OpenGraphMetadataArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Image       pulumi.StringPtrInput `pulumi:"image"`
	Title       pulumi.StringPtrInput `pulumi:"title"`
}

func (Apiv1OpenGraphMetadataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1OpenGraphMetadata)(nil)).Elem()
}

func (i Apiv1OpenGraphMetadataArgs) ToApiv1OpenGraphMetadataOutput() Apiv1OpenGraphMetadataOutput {
	return i.ToApiv1OpenGraphMetadataOutputWithContext(context.Background())
}

func (i Apiv1OpenGraphMetadataArgs) ToApiv1OpenGraphMetadataOutputWithContext(ctx context.Context) Apiv1OpenGraphMetadataOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Apiv1OpenGraphMetadataOutput)
}

func (i Apiv1OpenGraphMetadataArgs) ToApiv1OpenGraphMetadataPtrOutput() Apiv1OpenGraphMetadataPtrOutput {
	return i.ToApiv1OpenGraphMetadataPtrOutputWithContext(context.Background())
}

func (i Apiv1OpenGraphMetadataArgs) ToApiv1OpenGraphMetadataPtrOutputWithContext(ctx context.Context) Apiv1OpenGraphMetadataPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Apiv1OpenGraphMetadataOutput).ToApiv1OpenGraphMetadataPtrOutputWithContext(ctx)
}

// Apiv1OpenGraphMetadataPtrInput is an input type that accepts Apiv1OpenGraphMetadataArgs, Apiv1OpenGraphMetadataPtr and Apiv1OpenGraphMetadataPtrOutput values.
// You can construct a concrete instance of `Apiv1OpenGraphMetadataPtrInput` via:
//
//	        Apiv1OpenGraphMetadataArgs{...}
//
//	or:
//
//	        nil
type Apiv1OpenGraphMetadataPtrInput interface {
	pulumi.Input

	ToApiv1OpenGraphMetadataPtrOutput() Apiv1OpenGraphMetadataPtrOutput
	ToApiv1OpenGraphMetadataPtrOutputWithContext(context.Context) Apiv1OpenGraphMetadataPtrOutput
}

type apiv1OpenGraphMetadataPtrType Apiv1OpenGraphMetadataArgs

func Apiv1OpenGraphMetadataPtr(v *Apiv1OpenGraphMetadataArgs) Apiv1OpenGraphMetadataPtrInput {
	return (*apiv1OpenGraphMetadataPtrType)(v)
}

func (*apiv1OpenGraphMetadataPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1OpenGraphMetadata)(nil)).Elem()
}

func (i *apiv1OpenGraphMetadataPtrType) ToApiv1OpenGraphMetadataPtrOutput() Apiv1OpenGraphMetadataPtrOutput {
	return i.ToApiv1OpenGraphMetadataPtrOutputWithContext(context.Background())
}

func (i *apiv1OpenGraphMetadataPtrType) ToApiv1OpenGraphMetadataPtrOutputWithContext(ctx context.Context) Apiv1OpenGraphMetadataPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Apiv1OpenGraphMetadataPtrOutput)
}

type Apiv1OpenGraphMetadataOutput struct{ *pulumi.OutputState }

func (Apiv1OpenGraphMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1OpenGraphMetadata)(nil)).Elem()
}

func (o Apiv1OpenGraphMetadataOutput) ToApiv1OpenGraphMetadataOutput() Apiv1OpenGraphMetadataOutput {
	return o
}

func (o Apiv1OpenGraphMetadataOutput) ToApiv1OpenGraphMetadataOutputWithContext(ctx context.Context) Apiv1OpenGraphMetadataOutput {
	return o
}

func (o Apiv1OpenGraphMetadataOutput) ToApiv1OpenGraphMetadataPtrOutput() Apiv1OpenGraphMetadataPtrOutput {
	return o.ToApiv1OpenGraphMetadataPtrOutputWithContext(context.Background())
}

func (o Apiv1OpenGraphMetadataOutput) ToApiv1OpenGraphMetadataPtrOutputWithContext(ctx context.Context) Apiv1OpenGraphMetadataPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1OpenGraphMetadata) *Apiv1OpenGraphMetadata {
		return &v
	}).(Apiv1OpenGraphMetadataPtrOutput)
}

func (o Apiv1OpenGraphMetadataOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1OpenGraphMetadata) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o Apiv1OpenGraphMetadataOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1OpenGraphMetadata) *string { return v.Image }).(pulumi.StringPtrOutput)
}

func (o Apiv1OpenGraphMetadataOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1OpenGraphMetadata) *string { return v.Title }).(pulumi.StringPtrOutput)
}

type Apiv1OpenGraphMetadataPtrOutput struct{ *pulumi.OutputState }

func (Apiv1OpenGraphMetadataPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1OpenGraphMetadata)(nil)).Elem()
}

func (o Apiv1OpenGraphMetadataPtrOutput) ToApiv1OpenGraphMetadataPtrOutput() Apiv1OpenGraphMetadataPtrOutput {
	return o
}

func (o Apiv1OpenGraphMetadataPtrOutput) ToApiv1OpenGraphMetadataPtrOutputWithContext(ctx context.Context) Apiv1OpenGraphMetadataPtrOutput {
	return o
}

func (o Apiv1OpenGraphMetadataPtrOutput) Elem() Apiv1OpenGraphMetadataOutput {
	return o.ApplyT(func(v *Apiv1OpenGraphMetadata) Apiv1OpenGraphMetadata {
		if v != nil {
			return *v
		}
		var ret Apiv1OpenGraphMetadata
		return ret
	}).(Apiv1OpenGraphMetadataOutput)
}

func (o Apiv1OpenGraphMetadataPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1OpenGraphMetadata) *string {
		if v == nil {
			return nil
		}
		return v.Description
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1OpenGraphMetadataPtrOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1OpenGraphMetadata) *string {
		if v == nil {
			return nil
		}
		return v.Image
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1OpenGraphMetadataPtrOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1OpenGraphMetadata) *string {
		if v == nil {
			return nil
		}
		return v.Title
	}).(pulumi.StringPtrOutput)
}

type Apiv1Shortcut struct {
	CreatedTime *string                  `pulumi:"createdTime"`
	CreatorId   *int                     `pulumi:"creatorId"`
	Description *string                  `pulumi:"description"`
	Id          *int                     `pulumi:"id"`
	Link        *string                  `pulumi:"link"`
	Name        *string                  `pulumi:"name"`
	OgMetadata  *Apiv1OpenGraphMetadata  `pulumi:"ogMetadata"`
	RowStatus   *Apiv1ShortcutRowStatus  `pulumi:"rowStatus"`
	Tags        []string                 `pulumi:"tags"`
	Title       *string                  `pulumi:"title"`
	UpdatedTime *string                  `pulumi:"updatedTime"`
	ViewCount   *int                     `pulumi:"viewCount"`
	Visibility  *Apiv1ShortcutVisibility `pulumi:"visibility"`
}

// Defaults sets the appropriate defaults for Apiv1Shortcut
func (val *Apiv1Shortcut) Defaults() *Apiv1Shortcut {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.RowStatus == nil {
		rowStatus_ := Apiv1ShortcutRowStatus("ROW_STATUS_UNSPECIFIED")
		tmp.RowStatus = &rowStatus_
	}
	if tmp.Visibility == nil {
		visibility_ := Apiv1ShortcutVisibility("VISIBILITY_UNSPECIFIED")
		tmp.Visibility = &visibility_
	}
	return &tmp
}

type Apiv1ShortcutOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1Shortcut)(nil)).Elem()
}

func (o Apiv1ShortcutOutput) ToApiv1ShortcutOutput() Apiv1ShortcutOutput {
	return o
}

func (o Apiv1ShortcutOutput) ToApiv1ShortcutOutputWithContext(ctx context.Context) Apiv1ShortcutOutput {
	return o
}

func (o Apiv1ShortcutOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *string { return v.CreatedTime }).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutOutput) CreatorId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *int { return v.CreatorId }).(pulumi.IntPtrOutput)
}

func (o Apiv1ShortcutOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o Apiv1ShortcutOutput) Link() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *string { return v.Link }).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutOutput) OgMetadata() Apiv1OpenGraphMetadataPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *Apiv1OpenGraphMetadata { return v.OgMetadata }).(Apiv1OpenGraphMetadataPtrOutput)
}

func (o Apiv1ShortcutOutput) RowStatus() Apiv1ShortcutRowStatusPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *Apiv1ShortcutRowStatus { return v.RowStatus }).(Apiv1ShortcutRowStatusPtrOutput)
}

func (o Apiv1ShortcutOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Apiv1Shortcut) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o Apiv1ShortcutOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *string { return v.Title }).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutOutput) UpdatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *string { return v.UpdatedTime }).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutOutput) ViewCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *int { return v.ViewCount }).(pulumi.IntPtrOutput)
}

func (o Apiv1ShortcutOutput) Visibility() Apiv1ShortcutVisibilityPtrOutput {
	return o.ApplyT(func(v Apiv1Shortcut) *Apiv1ShortcutVisibility { return v.Visibility }).(Apiv1ShortcutVisibilityPtrOutput)
}

type Apiv1ShortcutPtrOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1Shortcut)(nil)).Elem()
}

func (o Apiv1ShortcutPtrOutput) ToApiv1ShortcutPtrOutput() Apiv1ShortcutPtrOutput {
	return o
}

func (o Apiv1ShortcutPtrOutput) ToApiv1ShortcutPtrOutputWithContext(ctx context.Context) Apiv1ShortcutPtrOutput {
	return o
}

func (o Apiv1ShortcutPtrOutput) Elem() Apiv1ShortcutOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) Apiv1Shortcut {
		if v != nil {
			return *v
		}
		var ret Apiv1Shortcut
		return ret
	}).(Apiv1ShortcutOutput)
}

func (o Apiv1ShortcutPtrOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *string {
		if v == nil {
			return nil
		}
		return v.CreatedTime
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) CreatorId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *int {
		if v == nil {
			return nil
		}
		return v.CreatorId
	}).(pulumi.IntPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *string {
		if v == nil {
			return nil
		}
		return v.Description
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *int {
		if v == nil {
			return nil
		}
		return v.Id
	}).(pulumi.IntPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) Link() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *string {
		if v == nil {
			return nil
		}
		return v.Link
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *string {
		if v == nil {
			return nil
		}
		return v.Name
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) OgMetadata() Apiv1OpenGraphMetadataPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *Apiv1OpenGraphMetadata {
		if v == nil {
			return nil
		}
		return v.OgMetadata
	}).(Apiv1OpenGraphMetadataPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) RowStatus() Apiv1ShortcutRowStatusPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *Apiv1ShortcutRowStatus {
		if v == nil {
			return nil
		}
		return v.RowStatus
	}).(Apiv1ShortcutRowStatusPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) []string {
		if v == nil {
			return nil
		}
		return v.Tags
	}).(pulumi.StringArrayOutput)
}

func (o Apiv1ShortcutPtrOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *string {
		if v == nil {
			return nil
		}
		return v.Title
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) UpdatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *string {
		if v == nil {
			return nil
		}
		return v.UpdatedTime
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) ViewCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *int {
		if v == nil {
			return nil
		}
		return v.ViewCount
	}).(pulumi.IntPtrOutput)
}

func (o Apiv1ShortcutPtrOutput) Visibility() Apiv1ShortcutVisibilityPtrOutput {
	return o.ApplyT(func(v *Apiv1Shortcut) *Apiv1ShortcutVisibility {
		if v == nil {
			return nil
		}
		return v.Visibility
	}).(Apiv1ShortcutVisibilityPtrOutput)
}

type Apiv1ShortcutArrayOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Apiv1Shortcut)(nil)).Elem()
}

func (o Apiv1ShortcutArrayOutput) ToApiv1ShortcutArrayOutput() Apiv1ShortcutArrayOutput {
	return o
}

func (o Apiv1ShortcutArrayOutput) ToApiv1ShortcutArrayOutputWithContext(ctx context.Context) Apiv1ShortcutArrayOutput {
	return o
}

func (o Apiv1ShortcutArrayOutput) Index(i pulumi.IntInput) Apiv1ShortcutOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Apiv1Shortcut {
		return vs[0].([]Apiv1Shortcut)[vs[1].(int)]
	}).(Apiv1ShortcutOutput)
}

type Apiv1UserSetting struct {
	ColorTheme *Apiv1UserSettingColorTheme `pulumi:"colorTheme"`
	// id is the user id.
	Id     *int                    `pulumi:"id"`
	Locale *Apiv1UserSettingLocale `pulumi:"locale"`
}

// Defaults sets the appropriate defaults for Apiv1UserSetting
func (val *Apiv1UserSetting) Defaults() *Apiv1UserSetting {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.ColorTheme == nil {
		colorTheme_ := Apiv1UserSettingColorTheme("COLOR_THEME_UNSPECIFIED")
		tmp.ColorTheme = &colorTheme_
	}
	if tmp.Locale == nil {
		locale_ := Apiv1UserSettingLocale("LOCALE_UNSPECIFIED")
		tmp.Locale = &locale_
	}
	return &tmp
}

type Apiv1UserSettingOutput struct{ *pulumi.OutputState }

func (Apiv1UserSettingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1UserSetting)(nil)).Elem()
}

func (o Apiv1UserSettingOutput) ToApiv1UserSettingOutput() Apiv1UserSettingOutput {
	return o
}

func (o Apiv1UserSettingOutput) ToApiv1UserSettingOutputWithContext(ctx context.Context) Apiv1UserSettingOutput {
	return o
}

func (o Apiv1UserSettingOutput) ColorTheme() Apiv1UserSettingColorThemePtrOutput {
	return o.ApplyT(func(v Apiv1UserSetting) *Apiv1UserSettingColorTheme { return v.ColorTheme }).(Apiv1UserSettingColorThemePtrOutput)
}

// id is the user id.
func (o Apiv1UserSettingOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Apiv1UserSetting) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o Apiv1UserSettingOutput) Locale() Apiv1UserSettingLocalePtrOutput {
	return o.ApplyT(func(v Apiv1UserSetting) *Apiv1UserSettingLocale { return v.Locale }).(Apiv1UserSettingLocalePtrOutput)
}

type Apiv1UserSettingPtrOutput struct{ *pulumi.OutputState }

func (Apiv1UserSettingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1UserSetting)(nil)).Elem()
}

func (o Apiv1UserSettingPtrOutput) ToApiv1UserSettingPtrOutput() Apiv1UserSettingPtrOutput {
	return o
}

func (o Apiv1UserSettingPtrOutput) ToApiv1UserSettingPtrOutputWithContext(ctx context.Context) Apiv1UserSettingPtrOutput {
	return o
}

func (o Apiv1UserSettingPtrOutput) Elem() Apiv1UserSettingOutput {
	return o.ApplyT(func(v *Apiv1UserSetting) Apiv1UserSetting {
		if v != nil {
			return *v
		}
		var ret Apiv1UserSetting
		return ret
	}).(Apiv1UserSettingOutput)
}

func (o Apiv1UserSettingPtrOutput) ColorTheme() Apiv1UserSettingColorThemePtrOutput {
	return o.ApplyT(func(v *Apiv1UserSetting) *Apiv1UserSettingColorTheme {
		if v == nil {
			return nil
		}
		return v.ColorTheme
	}).(Apiv1UserSettingColorThemePtrOutput)
}

// id is the user id.
func (o Apiv1UserSettingPtrOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Apiv1UserSetting) *int {
		if v == nil {
			return nil
		}
		return v.Id
	}).(pulumi.IntPtrOutput)
}

func (o Apiv1UserSettingPtrOutput) Locale() Apiv1UserSettingLocalePtrOutput {
	return o.ApplyT(func(v *Apiv1UserSetting) *Apiv1UserSettingLocale {
		if v == nil {
			return nil
		}
		return v.Locale
	}).(Apiv1UserSettingLocalePtrOutput)
}

type Apiv1WorkspaceSetting struct {
	AutoBackup *Apiv1AutoBackupWorkspaceSetting `pulumi:"autoBackup"`
	// The custom script.
	CustomScript *string `pulumi:"customScript"`
	// The custom style.
	CustomStyle       *string                                 `pulumi:"customStyle"`
	DefaultVisibility *Apiv1WorkspaceSettingDefaultVisibility `pulumi:"defaultVisibility"`
	// Whether to enable other users to sign up.
	EnableSignup *bool `pulumi:"enableSignup"`
	// The url of custom favicon provider.
	FaviconProvider *string `pulumi:"faviconProvider"`
	// The instance URL.
	InstanceUrl *string `pulumi:"instanceUrl"`
	LicenseKey  *string `pulumi:"licenseKey"`
}

// Defaults sets the appropriate defaults for Apiv1WorkspaceSetting
func (val *Apiv1WorkspaceSetting) Defaults() *Apiv1WorkspaceSetting {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.DefaultVisibility == nil {
		defaultVisibility_ := Apiv1WorkspaceSettingDefaultVisibility("VISIBILITY_UNSPECIFIED")
		tmp.DefaultVisibility = &defaultVisibility_
	}
	return &tmp
}

type Apiv1WorkspaceSettingOutput struct{ *pulumi.OutputState }

func (Apiv1WorkspaceSettingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1WorkspaceSetting)(nil)).Elem()
}

func (o Apiv1WorkspaceSettingOutput) ToApiv1WorkspaceSettingOutput() Apiv1WorkspaceSettingOutput {
	return o
}

func (o Apiv1WorkspaceSettingOutput) ToApiv1WorkspaceSettingOutputWithContext(ctx context.Context) Apiv1WorkspaceSettingOutput {
	return o
}

func (o Apiv1WorkspaceSettingOutput) AutoBackup() Apiv1AutoBackupWorkspaceSettingPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *Apiv1AutoBackupWorkspaceSetting { return v.AutoBackup }).(Apiv1AutoBackupWorkspaceSettingPtrOutput)
}

// The custom script.
func (o Apiv1WorkspaceSettingOutput) CustomScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *string { return v.CustomScript }).(pulumi.StringPtrOutput)
}

// The custom style.
func (o Apiv1WorkspaceSettingOutput) CustomStyle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *string { return v.CustomStyle }).(pulumi.StringPtrOutput)
}

func (o Apiv1WorkspaceSettingOutput) DefaultVisibility() Apiv1WorkspaceSettingDefaultVisibilityPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *Apiv1WorkspaceSettingDefaultVisibility { return v.DefaultVisibility }).(Apiv1WorkspaceSettingDefaultVisibilityPtrOutput)
}

// Whether to enable other users to sign up.
func (o Apiv1WorkspaceSettingOutput) EnableSignup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *bool { return v.EnableSignup }).(pulumi.BoolPtrOutput)
}

// The url of custom favicon provider.
func (o Apiv1WorkspaceSettingOutput) FaviconProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *string { return v.FaviconProvider }).(pulumi.StringPtrOutput)
}

// The instance URL.
func (o Apiv1WorkspaceSettingOutput) InstanceUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *string { return v.InstanceUrl }).(pulumi.StringPtrOutput)
}

func (o Apiv1WorkspaceSettingOutput) LicenseKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Apiv1WorkspaceSetting) *string { return v.LicenseKey }).(pulumi.StringPtrOutput)
}

type Apiv1WorkspaceSettingPtrOutput struct{ *pulumi.OutputState }

func (Apiv1WorkspaceSettingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1WorkspaceSetting)(nil)).Elem()
}

func (o Apiv1WorkspaceSettingPtrOutput) ToApiv1WorkspaceSettingPtrOutput() Apiv1WorkspaceSettingPtrOutput {
	return o
}

func (o Apiv1WorkspaceSettingPtrOutput) ToApiv1WorkspaceSettingPtrOutputWithContext(ctx context.Context) Apiv1WorkspaceSettingPtrOutput {
	return o
}

func (o Apiv1WorkspaceSettingPtrOutput) Elem() Apiv1WorkspaceSettingOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) Apiv1WorkspaceSetting {
		if v != nil {
			return *v
		}
		var ret Apiv1WorkspaceSetting
		return ret
	}).(Apiv1WorkspaceSettingOutput)
}

func (o Apiv1WorkspaceSettingPtrOutput) AutoBackup() Apiv1AutoBackupWorkspaceSettingPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *Apiv1AutoBackupWorkspaceSetting {
		if v == nil {
			return nil
		}
		return v.AutoBackup
	}).(Apiv1AutoBackupWorkspaceSettingPtrOutput)
}

// The custom script.
func (o Apiv1WorkspaceSettingPtrOutput) CustomScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *string {
		if v == nil {
			return nil
		}
		return v.CustomScript
	}).(pulumi.StringPtrOutput)
}

// The custom style.
func (o Apiv1WorkspaceSettingPtrOutput) CustomStyle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *string {
		if v == nil {
			return nil
		}
		return v.CustomStyle
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1WorkspaceSettingPtrOutput) DefaultVisibility() Apiv1WorkspaceSettingDefaultVisibilityPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *Apiv1WorkspaceSettingDefaultVisibility {
		if v == nil {
			return nil
		}
		return v.DefaultVisibility
	}).(Apiv1WorkspaceSettingDefaultVisibilityPtrOutput)
}

// Whether to enable other users to sign up.
func (o Apiv1WorkspaceSettingPtrOutput) EnableSignup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *bool {
		if v == nil {
			return nil
		}
		return v.EnableSignup
	}).(pulumi.BoolPtrOutput)
}

// The url of custom favicon provider.
func (o Apiv1WorkspaceSettingPtrOutput) FaviconProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *string {
		if v == nil {
			return nil
		}
		return v.FaviconProvider
	}).(pulumi.StringPtrOutput)
}

// The instance URL.
func (o Apiv1WorkspaceSettingPtrOutput) InstanceUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *string {
		if v == nil {
			return nil
		}
		return v.InstanceUrl
	}).(pulumi.StringPtrOutput)
}

func (o Apiv1WorkspaceSettingPtrOutput) LicenseKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSetting) *string {
		if v == nil {
			return nil
		}
		return v.LicenseKey
	}).(pulumi.StringPtrOutput)
}

type GetShortcutAnalyticsResponseAnalyticsItem struct {
	Count *int    `pulumi:"count"`
	Name  *string `pulumi:"name"`
}

type GetShortcutAnalyticsResponseAnalyticsItemOutput struct{ *pulumi.OutputState }

func (GetShortcutAnalyticsResponseAnalyticsItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetShortcutAnalyticsResponseAnalyticsItem)(nil)).Elem()
}

func (o GetShortcutAnalyticsResponseAnalyticsItemOutput) ToGetShortcutAnalyticsResponseAnalyticsItemOutput() GetShortcutAnalyticsResponseAnalyticsItemOutput {
	return o
}

func (o GetShortcutAnalyticsResponseAnalyticsItemOutput) ToGetShortcutAnalyticsResponseAnalyticsItemOutputWithContext(ctx context.Context) GetShortcutAnalyticsResponseAnalyticsItemOutput {
	return o
}

func (o GetShortcutAnalyticsResponseAnalyticsItemOutput) Count() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetShortcutAnalyticsResponseAnalyticsItem) *int { return v.Count }).(pulumi.IntPtrOutput)
}

func (o GetShortcutAnalyticsResponseAnalyticsItemOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetShortcutAnalyticsResponseAnalyticsItem) *string { return v.Name }).(pulumi.StringPtrOutput)
}

type GetShortcutAnalyticsResponseAnalyticsItemArrayOutput struct{ *pulumi.OutputState }

func (GetShortcutAnalyticsResponseAnalyticsItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetShortcutAnalyticsResponseAnalyticsItem)(nil)).Elem()
}

func (o GetShortcutAnalyticsResponseAnalyticsItemArrayOutput) ToGetShortcutAnalyticsResponseAnalyticsItemArrayOutput() GetShortcutAnalyticsResponseAnalyticsItemArrayOutput {
	return o
}

func (o GetShortcutAnalyticsResponseAnalyticsItemArrayOutput) ToGetShortcutAnalyticsResponseAnalyticsItemArrayOutputWithContext(ctx context.Context) GetShortcutAnalyticsResponseAnalyticsItemArrayOutput {
	return o
}

func (o GetShortcutAnalyticsResponseAnalyticsItemArrayOutput) Index(i pulumi.IntInput) GetShortcutAnalyticsResponseAnalyticsItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetShortcutAnalyticsResponseAnalyticsItem {
		return vs[0].([]GetShortcutAnalyticsResponseAnalyticsItem)[vs[1].(int)]
	}).(GetShortcutAnalyticsResponseAnalyticsItemOutput)
}

type V1GetCollectionResponse struct {
	Collection *Apiv1Collection `pulumi:"collection"`
}

// Defaults sets the appropriate defaults for V1GetCollectionResponse
func (val *V1GetCollectionResponse) Defaults() *V1GetCollectionResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Collection = tmp.Collection.Defaults()

	return &tmp
}

type V1GetCollectionResponseOutput struct{ *pulumi.OutputState }

func (V1GetCollectionResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetCollectionResponse)(nil)).Elem()
}

func (o V1GetCollectionResponseOutput) ToV1GetCollectionResponseOutput() V1GetCollectionResponseOutput {
	return o
}

func (o V1GetCollectionResponseOutput) ToV1GetCollectionResponseOutputWithContext(ctx context.Context) V1GetCollectionResponseOutput {
	return o
}

func (o V1GetCollectionResponseOutput) Collection() Apiv1CollectionPtrOutput {
	return o.ApplyT(func(v V1GetCollectionResponse) *Apiv1Collection { return v.Collection }).(Apiv1CollectionPtrOutput)
}

type V1GetShortcutAnalyticsResponse struct {
	Browsers   []GetShortcutAnalyticsResponseAnalyticsItem `pulumi:"browsers"`
	Devices    []GetShortcutAnalyticsResponseAnalyticsItem `pulumi:"devices"`
	References []GetShortcutAnalyticsResponseAnalyticsItem `pulumi:"references"`
}

type V1GetShortcutAnalyticsResponseOutput struct{ *pulumi.OutputState }

func (V1GetShortcutAnalyticsResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetShortcutAnalyticsResponse)(nil)).Elem()
}

func (o V1GetShortcutAnalyticsResponseOutput) ToV1GetShortcutAnalyticsResponseOutput() V1GetShortcutAnalyticsResponseOutput {
	return o
}

func (o V1GetShortcutAnalyticsResponseOutput) ToV1GetShortcutAnalyticsResponseOutputWithContext(ctx context.Context) V1GetShortcutAnalyticsResponseOutput {
	return o
}

func (o V1GetShortcutAnalyticsResponseOutput) Browsers() GetShortcutAnalyticsResponseAnalyticsItemArrayOutput {
	return o.ApplyT(func(v V1GetShortcutAnalyticsResponse) []GetShortcutAnalyticsResponseAnalyticsItem { return v.Browsers }).(GetShortcutAnalyticsResponseAnalyticsItemArrayOutput)
}

func (o V1GetShortcutAnalyticsResponseOutput) Devices() GetShortcutAnalyticsResponseAnalyticsItemArrayOutput {
	return o.ApplyT(func(v V1GetShortcutAnalyticsResponse) []GetShortcutAnalyticsResponseAnalyticsItem { return v.Devices }).(GetShortcutAnalyticsResponseAnalyticsItemArrayOutput)
}

func (o V1GetShortcutAnalyticsResponseOutput) References() GetShortcutAnalyticsResponseAnalyticsItemArrayOutput {
	return o.ApplyT(func(v V1GetShortcutAnalyticsResponse) []GetShortcutAnalyticsResponseAnalyticsItem {
		return v.References
	}).(GetShortcutAnalyticsResponseAnalyticsItemArrayOutput)
}

type V1GetShortcutResponse struct {
	Shortcut *Apiv1Shortcut `pulumi:"shortcut"`
}

// Defaults sets the appropriate defaults for V1GetShortcutResponse
func (val *V1GetShortcutResponse) Defaults() *V1GetShortcutResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Shortcut = tmp.Shortcut.Defaults()

	return &tmp
}

type V1GetShortcutResponseOutput struct{ *pulumi.OutputState }

func (V1GetShortcutResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetShortcutResponse)(nil)).Elem()
}

func (o V1GetShortcutResponseOutput) ToV1GetShortcutResponseOutput() V1GetShortcutResponseOutput {
	return o
}

func (o V1GetShortcutResponseOutput) ToV1GetShortcutResponseOutputWithContext(ctx context.Context) V1GetShortcutResponseOutput {
	return o
}

func (o V1GetShortcutResponseOutput) Shortcut() Apiv1ShortcutPtrOutput {
	return o.ApplyT(func(v V1GetShortcutResponse) *Apiv1Shortcut { return v.Shortcut }).(Apiv1ShortcutPtrOutput)
}

type V1GetUserResponse struct {
	User *V1User `pulumi:"user"`
}

// Defaults sets the appropriate defaults for V1GetUserResponse
func (val *V1GetUserResponse) Defaults() *V1GetUserResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.User = tmp.User.Defaults()

	return &tmp
}

type V1GetUserResponseOutput struct{ *pulumi.OutputState }

func (V1GetUserResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetUserResponse)(nil)).Elem()
}

func (o V1GetUserResponseOutput) ToV1GetUserResponseOutput() V1GetUserResponseOutput {
	return o
}

func (o V1GetUserResponseOutput) ToV1GetUserResponseOutputWithContext(ctx context.Context) V1GetUserResponseOutput {
	return o
}

func (o V1GetUserResponseOutput) User() V1UserPtrOutput {
	return o.ApplyT(func(v V1GetUserResponse) *V1User { return v.User }).(V1UserPtrOutput)
}

type V1GetUserSettingResponse struct {
	UserSetting *Apiv1UserSetting `pulumi:"userSetting"`
}

// Defaults sets the appropriate defaults for V1GetUserSettingResponse
func (val *V1GetUserSettingResponse) Defaults() *V1GetUserSettingResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.UserSetting = tmp.UserSetting.Defaults()

	return &tmp
}

type V1GetUserSettingResponseOutput struct{ *pulumi.OutputState }

func (V1GetUserSettingResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetUserSettingResponse)(nil)).Elem()
}

func (o V1GetUserSettingResponseOutput) ToV1GetUserSettingResponseOutput() V1GetUserSettingResponseOutput {
	return o
}

func (o V1GetUserSettingResponseOutput) ToV1GetUserSettingResponseOutputWithContext(ctx context.Context) V1GetUserSettingResponseOutput {
	return o
}

func (o V1GetUserSettingResponseOutput) UserSetting() Apiv1UserSettingPtrOutput {
	return o.ApplyT(func(v V1GetUserSettingResponse) *Apiv1UserSetting { return v.UserSetting }).(Apiv1UserSettingPtrOutput)
}

type V1GetWorkspaceProfileResponse struct {
	Profile *V1WorkspaceProfile `pulumi:"profile"`
}

// Defaults sets the appropriate defaults for V1GetWorkspaceProfileResponse
func (val *V1GetWorkspaceProfileResponse) Defaults() *V1GetWorkspaceProfileResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Profile = tmp.Profile.Defaults()

	return &tmp
}

type V1GetWorkspaceProfileResponseOutput struct{ *pulumi.OutputState }

func (V1GetWorkspaceProfileResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetWorkspaceProfileResponse)(nil)).Elem()
}

func (o V1GetWorkspaceProfileResponseOutput) ToV1GetWorkspaceProfileResponseOutput() V1GetWorkspaceProfileResponseOutput {
	return o
}

func (o V1GetWorkspaceProfileResponseOutput) ToV1GetWorkspaceProfileResponseOutputWithContext(ctx context.Context) V1GetWorkspaceProfileResponseOutput {
	return o
}

func (o V1GetWorkspaceProfileResponseOutput) Profile() V1WorkspaceProfilePtrOutput {
	return o.ApplyT(func(v V1GetWorkspaceProfileResponse) *V1WorkspaceProfile { return v.Profile }).(V1WorkspaceProfilePtrOutput)
}

type V1GetWorkspaceSettingResponse struct {
	Setting *Apiv1WorkspaceSetting `pulumi:"setting"`
}

// Defaults sets the appropriate defaults for V1GetWorkspaceSettingResponse
func (val *V1GetWorkspaceSettingResponse) Defaults() *V1GetWorkspaceSettingResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Setting = tmp.Setting.Defaults()

	return &tmp
}

type V1GetWorkspaceSettingResponseOutput struct{ *pulumi.OutputState }

func (V1GetWorkspaceSettingResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1GetWorkspaceSettingResponse)(nil)).Elem()
}

func (o V1GetWorkspaceSettingResponseOutput) ToV1GetWorkspaceSettingResponseOutput() V1GetWorkspaceSettingResponseOutput {
	return o
}

func (o V1GetWorkspaceSettingResponseOutput) ToV1GetWorkspaceSettingResponseOutputWithContext(ctx context.Context) V1GetWorkspaceSettingResponseOutput {
	return o
}

func (o V1GetWorkspaceSettingResponseOutput) Setting() Apiv1WorkspaceSettingPtrOutput {
	return o.ApplyT(func(v V1GetWorkspaceSettingResponse) *Apiv1WorkspaceSetting { return v.Setting }).(Apiv1WorkspaceSettingPtrOutput)
}

type V1ListCollectionsResponse struct {
	Collections []Apiv1Collection `pulumi:"collections"`
}

type V1ListCollectionsResponseOutput struct{ *pulumi.OutputState }

func (V1ListCollectionsResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1ListCollectionsResponse)(nil)).Elem()
}

func (o V1ListCollectionsResponseOutput) ToV1ListCollectionsResponseOutput() V1ListCollectionsResponseOutput {
	return o
}

func (o V1ListCollectionsResponseOutput) ToV1ListCollectionsResponseOutputWithContext(ctx context.Context) V1ListCollectionsResponseOutput {
	return o
}

func (o V1ListCollectionsResponseOutput) Collections() Apiv1CollectionArrayOutput {
	return o.ApplyT(func(v V1ListCollectionsResponse) []Apiv1Collection { return v.Collections }).(Apiv1CollectionArrayOutput)
}

type V1ListShortcutsResponse struct {
	Shortcuts []Apiv1Shortcut `pulumi:"shortcuts"`
}

type V1ListShortcutsResponseOutput struct{ *pulumi.OutputState }

func (V1ListShortcutsResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1ListShortcutsResponse)(nil)).Elem()
}

func (o V1ListShortcutsResponseOutput) ToV1ListShortcutsResponseOutput() V1ListShortcutsResponseOutput {
	return o
}

func (o V1ListShortcutsResponseOutput) ToV1ListShortcutsResponseOutputWithContext(ctx context.Context) V1ListShortcutsResponseOutput {
	return o
}

func (o V1ListShortcutsResponseOutput) Shortcuts() Apiv1ShortcutArrayOutput {
	return o.ApplyT(func(v V1ListShortcutsResponse) []Apiv1Shortcut { return v.Shortcuts }).(Apiv1ShortcutArrayOutput)
}

type V1ListUserAccessTokensResponse struct {
	AccessTokens []V1UserAccessToken `pulumi:"accessTokens"`
}

type V1ListUserAccessTokensResponseOutput struct{ *pulumi.OutputState }

func (V1ListUserAccessTokensResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1ListUserAccessTokensResponse)(nil)).Elem()
}

func (o V1ListUserAccessTokensResponseOutput) ToV1ListUserAccessTokensResponseOutput() V1ListUserAccessTokensResponseOutput {
	return o
}

func (o V1ListUserAccessTokensResponseOutput) ToV1ListUserAccessTokensResponseOutputWithContext(ctx context.Context) V1ListUserAccessTokensResponseOutput {
	return o
}

func (o V1ListUserAccessTokensResponseOutput) AccessTokens() V1UserAccessTokenArrayOutput {
	return o.ApplyT(func(v V1ListUserAccessTokensResponse) []V1UserAccessToken { return v.AccessTokens }).(V1UserAccessTokenArrayOutput)
}

type V1ListUsersResponse struct {
	Users []V1User `pulumi:"users"`
}

type V1ListUsersResponseOutput struct{ *pulumi.OutputState }

func (V1ListUsersResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1ListUsersResponse)(nil)).Elem()
}

func (o V1ListUsersResponseOutput) ToV1ListUsersResponseOutput() V1ListUsersResponseOutput {
	return o
}

func (o V1ListUsersResponseOutput) ToV1ListUsersResponseOutputWithContext(ctx context.Context) V1ListUsersResponseOutput {
	return o
}

func (o V1ListUsersResponseOutput) Users() V1UserArrayOutput {
	return o.ApplyT(func(v V1ListUsersResponse) []V1User { return v.Users }).(V1UserArrayOutput)
}

type V1User struct {
	CreatedTime *string          `pulumi:"createdTime"`
	Email       *string          `pulumi:"email"`
	Id          *int             `pulumi:"id"`
	Nickname    *string          `pulumi:"nickname"`
	Password    *string          `pulumi:"password"`
	Role        *V1UserRole      `pulumi:"role"`
	RowStatus   *V1UserRowStatus `pulumi:"rowStatus"`
	UpdatedTime *string          `pulumi:"updatedTime"`
}

// Defaults sets the appropriate defaults for V1User
func (val *V1User) Defaults() *V1User {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Role == nil {
		role_ := V1UserRole("ROLE_UNSPECIFIED")
		tmp.Role = &role_
	}
	if tmp.RowStatus == nil {
		rowStatus_ := V1UserRowStatus("ROW_STATUS_UNSPECIFIED")
		tmp.RowStatus = &rowStatus_
	}
	return &tmp
}

type V1UserOutput struct{ *pulumi.OutputState }

func (V1UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1User)(nil)).Elem()
}

func (o V1UserOutput) ToV1UserOutput() V1UserOutput {
	return o
}

func (o V1UserOutput) ToV1UserOutputWithContext(ctx context.Context) V1UserOutput {
	return o
}

func (o V1UserOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1User) *string { return v.CreatedTime }).(pulumi.StringPtrOutput)
}

func (o V1UserOutput) Email() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1User) *string { return v.Email }).(pulumi.StringPtrOutput)
}

func (o V1UserOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v V1User) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o V1UserOutput) Nickname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1User) *string { return v.Nickname }).(pulumi.StringPtrOutput)
}

func (o V1UserOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1User) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o V1UserOutput) Role() V1UserRolePtrOutput {
	return o.ApplyT(func(v V1User) *V1UserRole { return v.Role }).(V1UserRolePtrOutput)
}

func (o V1UserOutput) RowStatus() V1UserRowStatusPtrOutput {
	return o.ApplyT(func(v V1User) *V1UserRowStatus { return v.RowStatus }).(V1UserRowStatusPtrOutput)
}

func (o V1UserOutput) UpdatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1User) *string { return v.UpdatedTime }).(pulumi.StringPtrOutput)
}

type V1UserPtrOutput struct{ *pulumi.OutputState }

func (V1UserPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**V1User)(nil)).Elem()
}

func (o V1UserPtrOutput) ToV1UserPtrOutput() V1UserPtrOutput {
	return o
}

func (o V1UserPtrOutput) ToV1UserPtrOutputWithContext(ctx context.Context) V1UserPtrOutput {
	return o
}

func (o V1UserPtrOutput) Elem() V1UserOutput {
	return o.ApplyT(func(v *V1User) V1User {
		if v != nil {
			return *v
		}
		var ret V1User
		return ret
	}).(V1UserOutput)
}

func (o V1UserPtrOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1User) *string {
		if v == nil {
			return nil
		}
		return v.CreatedTime
	}).(pulumi.StringPtrOutput)
}

func (o V1UserPtrOutput) Email() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1User) *string {
		if v == nil {
			return nil
		}
		return v.Email
	}).(pulumi.StringPtrOutput)
}

func (o V1UserPtrOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *V1User) *int {
		if v == nil {
			return nil
		}
		return v.Id
	}).(pulumi.IntPtrOutput)
}

func (o V1UserPtrOutput) Nickname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1User) *string {
		if v == nil {
			return nil
		}
		return v.Nickname
	}).(pulumi.StringPtrOutput)
}

func (o V1UserPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1User) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

func (o V1UserPtrOutput) Role() V1UserRolePtrOutput {
	return o.ApplyT(func(v *V1User) *V1UserRole {
		if v == nil {
			return nil
		}
		return v.Role
	}).(V1UserRolePtrOutput)
}

func (o V1UserPtrOutput) RowStatus() V1UserRowStatusPtrOutput {
	return o.ApplyT(func(v *V1User) *V1UserRowStatus {
		if v == nil {
			return nil
		}
		return v.RowStatus
	}).(V1UserRowStatusPtrOutput)
}

func (o V1UserPtrOutput) UpdatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1User) *string {
		if v == nil {
			return nil
		}
		return v.UpdatedTime
	}).(pulumi.StringPtrOutput)
}

type V1UserArrayOutput struct{ *pulumi.OutputState }

func (V1UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]V1User)(nil)).Elem()
}

func (o V1UserArrayOutput) ToV1UserArrayOutput() V1UserArrayOutput {
	return o
}

func (o V1UserArrayOutput) ToV1UserArrayOutputWithContext(ctx context.Context) V1UserArrayOutput {
	return o
}

func (o V1UserArrayOutput) Index(i pulumi.IntInput) V1UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) V1User {
		return vs[0].([]V1User)[vs[1].(int)]
	}).(V1UserOutput)
}

type V1UserAccessToken struct {
	AccessToken *string `pulumi:"accessToken"`
	Description *string `pulumi:"description"`
	ExpiresAt   *string `pulumi:"expiresAt"`
	IssuedAt    *string `pulumi:"issuedAt"`
}

type V1UserAccessTokenOutput struct{ *pulumi.OutputState }

func (V1UserAccessTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1UserAccessToken)(nil)).Elem()
}

func (o V1UserAccessTokenOutput) ToV1UserAccessTokenOutput() V1UserAccessTokenOutput {
	return o
}

func (o V1UserAccessTokenOutput) ToV1UserAccessTokenOutputWithContext(ctx context.Context) V1UserAccessTokenOutput {
	return o
}

func (o V1UserAccessTokenOutput) AccessToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1UserAccessToken) *string { return v.AccessToken }).(pulumi.StringPtrOutput)
}

func (o V1UserAccessTokenOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1UserAccessToken) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o V1UserAccessTokenOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1UserAccessToken) *string { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

func (o V1UserAccessTokenOutput) IssuedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1UserAccessToken) *string { return v.IssuedAt }).(pulumi.StringPtrOutput)
}

type V1UserAccessTokenPtrOutput struct{ *pulumi.OutputState }

func (V1UserAccessTokenPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**V1UserAccessToken)(nil)).Elem()
}

func (o V1UserAccessTokenPtrOutput) ToV1UserAccessTokenPtrOutput() V1UserAccessTokenPtrOutput {
	return o
}

func (o V1UserAccessTokenPtrOutput) ToV1UserAccessTokenPtrOutputWithContext(ctx context.Context) V1UserAccessTokenPtrOutput {
	return o
}

func (o V1UserAccessTokenPtrOutput) Elem() V1UserAccessTokenOutput {
	return o.ApplyT(func(v *V1UserAccessToken) V1UserAccessToken {
		if v != nil {
			return *v
		}
		var ret V1UserAccessToken
		return ret
	}).(V1UserAccessTokenOutput)
}

func (o V1UserAccessTokenPtrOutput) AccessToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1UserAccessToken) *string {
		if v == nil {
			return nil
		}
		return v.AccessToken
	}).(pulumi.StringPtrOutput)
}

func (o V1UserAccessTokenPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1UserAccessToken) *string {
		if v == nil {
			return nil
		}
		return v.Description
	}).(pulumi.StringPtrOutput)
}

func (o V1UserAccessTokenPtrOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1UserAccessToken) *string {
		if v == nil {
			return nil
		}
		return v.ExpiresAt
	}).(pulumi.StringPtrOutput)
}

func (o V1UserAccessTokenPtrOutput) IssuedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1UserAccessToken) *string {
		if v == nil {
			return nil
		}
		return v.IssuedAt
	}).(pulumi.StringPtrOutput)
}

type V1UserAccessTokenArrayOutput struct{ *pulumi.OutputState }

func (V1UserAccessTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]V1UserAccessToken)(nil)).Elem()
}

func (o V1UserAccessTokenArrayOutput) ToV1UserAccessTokenArrayOutput() V1UserAccessTokenArrayOutput {
	return o
}

func (o V1UserAccessTokenArrayOutput) ToV1UserAccessTokenArrayOutputWithContext(ctx context.Context) V1UserAccessTokenArrayOutput {
	return o
}

func (o V1UserAccessTokenArrayOutput) Index(i pulumi.IntInput) V1UserAccessTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) V1UserAccessToken {
		return vs[0].([]V1UserAccessToken)[vs[1].(int)]
	}).(V1UserAccessTokenOutput)
}

type V1WorkspaceProfile struct {
	// The custom script.
	CustomScript *string `pulumi:"customScript"`
	// The custom style.
	CustomStyle *string `pulumi:"customStyle"`
	// Whether to enable other users to sign up.
	EnableSignup *bool `pulumi:"enableSignup"`
	// The url of custom favicon provider.
	FaviconProvider *string `pulumi:"faviconProvider"`
	// Current workspace mode: dev, prod.
	Mode  *string                 `pulumi:"mode"`
	Owner *string                 `pulumi:"owner"`
	Plan  *V1WorkspaceProfilePlan `pulumi:"plan"`
	// Current workspace version.
	Version *string `pulumi:"version"`
}

// Defaults sets the appropriate defaults for V1WorkspaceProfile
func (val *V1WorkspaceProfile) Defaults() *V1WorkspaceProfile {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Plan == nil {
		plan_ := V1WorkspaceProfilePlan("PLAN_TYPE_UNSPECIFIED")
		tmp.Plan = &plan_
	}
	return &tmp
}

type V1WorkspaceProfileOutput struct{ *pulumi.OutputState }

func (V1WorkspaceProfileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1WorkspaceProfile)(nil)).Elem()
}

func (o V1WorkspaceProfileOutput) ToV1WorkspaceProfileOutput() V1WorkspaceProfileOutput {
	return o
}

func (o V1WorkspaceProfileOutput) ToV1WorkspaceProfileOutputWithContext(ctx context.Context) V1WorkspaceProfileOutput {
	return o
}

// The custom script.
func (o V1WorkspaceProfileOutput) CustomScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *string { return v.CustomScript }).(pulumi.StringPtrOutput)
}

// The custom style.
func (o V1WorkspaceProfileOutput) CustomStyle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *string { return v.CustomStyle }).(pulumi.StringPtrOutput)
}

// Whether to enable other users to sign up.
func (o V1WorkspaceProfileOutput) EnableSignup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *bool { return v.EnableSignup }).(pulumi.BoolPtrOutput)
}

// The url of custom favicon provider.
func (o V1WorkspaceProfileOutput) FaviconProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *string { return v.FaviconProvider }).(pulumi.StringPtrOutput)
}

// Current workspace mode: dev, prod.
func (o V1WorkspaceProfileOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *string { return v.Mode }).(pulumi.StringPtrOutput)
}

func (o V1WorkspaceProfileOutput) Owner() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *string { return v.Owner }).(pulumi.StringPtrOutput)
}

func (o V1WorkspaceProfileOutput) Plan() V1WorkspaceProfilePlanPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *V1WorkspaceProfilePlan { return v.Plan }).(V1WorkspaceProfilePlanPtrOutput)
}

// Current workspace version.
func (o V1WorkspaceProfileOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v V1WorkspaceProfile) *string { return v.Version }).(pulumi.StringPtrOutput)
}

type V1WorkspaceProfilePtrOutput struct{ *pulumi.OutputState }

func (V1WorkspaceProfilePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**V1WorkspaceProfile)(nil)).Elem()
}

func (o V1WorkspaceProfilePtrOutput) ToV1WorkspaceProfilePtrOutput() V1WorkspaceProfilePtrOutput {
	return o
}

func (o V1WorkspaceProfilePtrOutput) ToV1WorkspaceProfilePtrOutputWithContext(ctx context.Context) V1WorkspaceProfilePtrOutput {
	return o
}

func (o V1WorkspaceProfilePtrOutput) Elem() V1WorkspaceProfileOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) V1WorkspaceProfile {
		if v != nil {
			return *v
		}
		var ret V1WorkspaceProfile
		return ret
	}).(V1WorkspaceProfileOutput)
}

// The custom script.
func (o V1WorkspaceProfilePtrOutput) CustomScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *string {
		if v == nil {
			return nil
		}
		return v.CustomScript
	}).(pulumi.StringPtrOutput)
}

// The custom style.
func (o V1WorkspaceProfilePtrOutput) CustomStyle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *string {
		if v == nil {
			return nil
		}
		return v.CustomStyle
	}).(pulumi.StringPtrOutput)
}

// Whether to enable other users to sign up.
func (o V1WorkspaceProfilePtrOutput) EnableSignup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *bool {
		if v == nil {
			return nil
		}
		return v.EnableSignup
	}).(pulumi.BoolPtrOutput)
}

// The url of custom favicon provider.
func (o V1WorkspaceProfilePtrOutput) FaviconProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *string {
		if v == nil {
			return nil
		}
		return v.FaviconProvider
	}).(pulumi.StringPtrOutput)
}

// Current workspace mode: dev, prod.
func (o V1WorkspaceProfilePtrOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *string {
		if v == nil {
			return nil
		}
		return v.Mode
	}).(pulumi.StringPtrOutput)
}

func (o V1WorkspaceProfilePtrOutput) Owner() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *string {
		if v == nil {
			return nil
		}
		return v.Owner
	}).(pulumi.StringPtrOutput)
}

func (o V1WorkspaceProfilePtrOutput) Plan() V1WorkspaceProfilePlanPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *V1WorkspaceProfilePlan {
		if v == nil {
			return nil
		}
		return v.Plan
	}).(V1WorkspaceProfilePlanPtrOutput)
}

// Current workspace version.
func (o V1WorkspaceProfilePtrOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *V1WorkspaceProfile) *string {
		if v == nil {
			return nil
		}
		return v.Version
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*Apiv1OpenGraphMetadataInput)(nil)).Elem(), Apiv1OpenGraphMetadataArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Apiv1OpenGraphMetadataPtrInput)(nil)).Elem(), Apiv1OpenGraphMetadataArgs{})
	pulumi.RegisterOutputType(Apiv1AutoBackupWorkspaceSettingOutput{})
	pulumi.RegisterOutputType(Apiv1AutoBackupWorkspaceSettingPtrOutput{})
	pulumi.RegisterOutputType(Apiv1CollectionOutput{})
	pulumi.RegisterOutputType(Apiv1CollectionPtrOutput{})
	pulumi.RegisterOutputType(Apiv1CollectionArrayOutput{})
	pulumi.RegisterOutputType(Apiv1OpenGraphMetadataOutput{})
	pulumi.RegisterOutputType(Apiv1OpenGraphMetadataPtrOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutPtrOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutArrayOutput{})
	pulumi.RegisterOutputType(Apiv1UserSettingOutput{})
	pulumi.RegisterOutputType(Apiv1UserSettingPtrOutput{})
	pulumi.RegisterOutputType(Apiv1WorkspaceSettingOutput{})
	pulumi.RegisterOutputType(Apiv1WorkspaceSettingPtrOutput{})
	pulumi.RegisterOutputType(GetShortcutAnalyticsResponseAnalyticsItemOutput{})
	pulumi.RegisterOutputType(GetShortcutAnalyticsResponseAnalyticsItemArrayOutput{})
	pulumi.RegisterOutputType(V1GetCollectionResponseOutput{})
	pulumi.RegisterOutputType(V1GetShortcutAnalyticsResponseOutput{})
	pulumi.RegisterOutputType(V1GetShortcutResponseOutput{})
	pulumi.RegisterOutputType(V1GetUserResponseOutput{})
	pulumi.RegisterOutputType(V1GetUserSettingResponseOutput{})
	pulumi.RegisterOutputType(V1GetWorkspaceProfileResponseOutput{})
	pulumi.RegisterOutputType(V1GetWorkspaceSettingResponseOutput{})
	pulumi.RegisterOutputType(V1ListCollectionsResponseOutput{})
	pulumi.RegisterOutputType(V1ListShortcutsResponseOutput{})
	pulumi.RegisterOutputType(V1ListUserAccessTokensResponseOutput{})
	pulumi.RegisterOutputType(V1ListUsersResponseOutput{})
	pulumi.RegisterOutputType(V1UserOutput{})
	pulumi.RegisterOutputType(V1UserPtrOutput{})
	pulumi.RegisterOutputType(V1UserArrayOutput{})
	pulumi.RegisterOutputType(V1UserAccessTokenOutput{})
	pulumi.RegisterOutputType(V1UserAccessTokenPtrOutput{})
	pulumi.RegisterOutputType(V1UserAccessTokenArrayOutput{})
	pulumi.RegisterOutputType(V1WorkspaceProfileOutput{})
	pulumi.RegisterOutputType(V1WorkspaceProfilePtrOutput{})
}
