// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Apiv1CollectionVisibility string

const (
	Apiv1CollectionVisibilityVisibilityUnspecified = Apiv1CollectionVisibility("VISIBILITY_UNSPECIFIED")
	Apiv1CollectionVisibilityPrivate               = Apiv1CollectionVisibility("PRIVATE")
	Apiv1CollectionVisibilityWorkspace             = Apiv1CollectionVisibility("WORKSPACE")
	Apiv1CollectionVisibilityPublic                = Apiv1CollectionVisibility("PUBLIC")
)

type Apiv1CollectionVisibilityOutput struct{ *pulumi.OutputState }

func (Apiv1CollectionVisibilityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1CollectionVisibility)(nil)).Elem()
}

func (o Apiv1CollectionVisibilityOutput) ToApiv1CollectionVisibilityOutput() Apiv1CollectionVisibilityOutput {
	return o
}

func (o Apiv1CollectionVisibilityOutput) ToApiv1CollectionVisibilityOutputWithContext(ctx context.Context) Apiv1CollectionVisibilityOutput {
	return o
}

func (o Apiv1CollectionVisibilityOutput) ToApiv1CollectionVisibilityPtrOutput() Apiv1CollectionVisibilityPtrOutput {
	return o.ToApiv1CollectionVisibilityPtrOutputWithContext(context.Background())
}

func (o Apiv1CollectionVisibilityOutput) ToApiv1CollectionVisibilityPtrOutputWithContext(ctx context.Context) Apiv1CollectionVisibilityPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1CollectionVisibility) *Apiv1CollectionVisibility {
		return &v
	}).(Apiv1CollectionVisibilityPtrOutput)
}

func (o Apiv1CollectionVisibilityOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1CollectionVisibilityOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1CollectionVisibility) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1CollectionVisibilityOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1CollectionVisibilityOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1CollectionVisibility) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1CollectionVisibilityPtrOutput struct{ *pulumi.OutputState }

func (Apiv1CollectionVisibilityPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1CollectionVisibility)(nil)).Elem()
}

func (o Apiv1CollectionVisibilityPtrOutput) ToApiv1CollectionVisibilityPtrOutput() Apiv1CollectionVisibilityPtrOutput {
	return o
}

func (o Apiv1CollectionVisibilityPtrOutput) ToApiv1CollectionVisibilityPtrOutputWithContext(ctx context.Context) Apiv1CollectionVisibilityPtrOutput {
	return o
}

func (o Apiv1CollectionVisibilityPtrOutput) Elem() Apiv1CollectionVisibilityOutput {
	return o.ApplyT(func(v *Apiv1CollectionVisibility) Apiv1CollectionVisibility {
		if v != nil {
			return *v
		}
		var ret Apiv1CollectionVisibility
		return ret
	}).(Apiv1CollectionVisibilityOutput)
}

func (o Apiv1CollectionVisibilityPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1CollectionVisibilityPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1CollectionVisibility) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutRowStatus string

const (
	Apiv1ShortcutRowStatusRowStatusUnspecified = Apiv1ShortcutRowStatus("ROW_STATUS_UNSPECIFIED")
	Apiv1ShortcutRowStatusNormal               = Apiv1ShortcutRowStatus("NORMAL")
	Apiv1ShortcutRowStatusArchived             = Apiv1ShortcutRowStatus("ARCHIVED")
)

type Apiv1ShortcutRowStatusOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutRowStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1ShortcutRowStatus)(nil)).Elem()
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusOutput() Apiv1ShortcutRowStatusOutput {
	return o
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusOutputWithContext(ctx context.Context) Apiv1ShortcutRowStatusOutput {
	return o
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusPtrOutput() Apiv1ShortcutRowStatusPtrOutput {
	return o.ToApiv1ShortcutRowStatusPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusOutput) ToApiv1ShortcutRowStatusPtrOutputWithContext(ctx context.Context) Apiv1ShortcutRowStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1ShortcutRowStatus) *Apiv1ShortcutRowStatus {
		return &v
	}).(Apiv1ShortcutRowStatusPtrOutput)
}

func (o Apiv1ShortcutRowStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutRowStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1ShortcutRowStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutRowStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutRowStatusPtrOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutRowStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1ShortcutRowStatus)(nil)).Elem()
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToApiv1ShortcutRowStatusPtrOutput() Apiv1ShortcutRowStatusPtrOutput {
	return o
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToApiv1ShortcutRowStatusPtrOutputWithContext(ctx context.Context) Apiv1ShortcutRowStatusPtrOutput {
	return o
}

func (o Apiv1ShortcutRowStatusPtrOutput) Elem() Apiv1ShortcutRowStatusOutput {
	return o.ApplyT(func(v *Apiv1ShortcutRowStatus) Apiv1ShortcutRowStatus {
		if v != nil {
			return *v
		}
		var ret Apiv1ShortcutRowStatus
		return ret
	}).(Apiv1ShortcutRowStatusOutput)
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutRowStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1ShortcutRowStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutVisibility string

const (
	Apiv1ShortcutVisibilityVisibilityUnspecified = Apiv1ShortcutVisibility("VISIBILITY_UNSPECIFIED")
	Apiv1ShortcutVisibilityPrivate               = Apiv1ShortcutVisibility("PRIVATE")
	Apiv1ShortcutVisibilityWorkspace             = Apiv1ShortcutVisibility("WORKSPACE")
	Apiv1ShortcutVisibilityPublic                = Apiv1ShortcutVisibility("PUBLIC")
)

type Apiv1ShortcutVisibilityOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutVisibilityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1ShortcutVisibility)(nil)).Elem()
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityOutput() Apiv1ShortcutVisibilityOutput {
	return o
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityOutputWithContext(ctx context.Context) Apiv1ShortcutVisibilityOutput {
	return o
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityPtrOutput() Apiv1ShortcutVisibilityPtrOutput {
	return o.ToApiv1ShortcutVisibilityPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityOutput) ToApiv1ShortcutVisibilityPtrOutputWithContext(ctx context.Context) Apiv1ShortcutVisibilityPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1ShortcutVisibility) *Apiv1ShortcutVisibility {
		return &v
	}).(Apiv1ShortcutVisibilityPtrOutput)
}

func (o Apiv1ShortcutVisibilityOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutVisibility) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1ShortcutVisibilityOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1ShortcutVisibility) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1ShortcutVisibilityPtrOutput struct{ *pulumi.OutputState }

func (Apiv1ShortcutVisibilityPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1ShortcutVisibility)(nil)).Elem()
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToApiv1ShortcutVisibilityPtrOutput() Apiv1ShortcutVisibilityPtrOutput {
	return o
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToApiv1ShortcutVisibilityPtrOutputWithContext(ctx context.Context) Apiv1ShortcutVisibilityPtrOutput {
	return o
}

func (o Apiv1ShortcutVisibilityPtrOutput) Elem() Apiv1ShortcutVisibilityOutput {
	return o.ApplyT(func(v *Apiv1ShortcutVisibility) Apiv1ShortcutVisibility {
		if v != nil {
			return *v
		}
		var ret Apiv1ShortcutVisibility
		return ret
	}).(Apiv1ShortcutVisibilityOutput)
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1ShortcutVisibilityPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1ShortcutVisibility) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1UserSettingColorTheme string

const (
	Apiv1UserSettingColorThemeColorThemeUnspecified = Apiv1UserSettingColorTheme("COLOR_THEME_UNSPECIFIED")
	Apiv1UserSettingColorThemeColorThemeSystem      = Apiv1UserSettingColorTheme("COLOR_THEME_SYSTEM")
	Apiv1UserSettingColorThemeColorThemeLight       = Apiv1UserSettingColorTheme("COLOR_THEME_LIGHT")
	Apiv1UserSettingColorThemeColorThemeDark        = Apiv1UserSettingColorTheme("COLOR_THEME_DARK")
)

type Apiv1UserSettingColorThemeOutput struct{ *pulumi.OutputState }

func (Apiv1UserSettingColorThemeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1UserSettingColorTheme)(nil)).Elem()
}

func (o Apiv1UserSettingColorThemeOutput) ToApiv1UserSettingColorThemeOutput() Apiv1UserSettingColorThemeOutput {
	return o
}

func (o Apiv1UserSettingColorThemeOutput) ToApiv1UserSettingColorThemeOutputWithContext(ctx context.Context) Apiv1UserSettingColorThemeOutput {
	return o
}

func (o Apiv1UserSettingColorThemeOutput) ToApiv1UserSettingColorThemePtrOutput() Apiv1UserSettingColorThemePtrOutput {
	return o.ToApiv1UserSettingColorThemePtrOutputWithContext(context.Background())
}

func (o Apiv1UserSettingColorThemeOutput) ToApiv1UserSettingColorThemePtrOutputWithContext(ctx context.Context) Apiv1UserSettingColorThemePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1UserSettingColorTheme) *Apiv1UserSettingColorTheme {
		return &v
	}).(Apiv1UserSettingColorThemePtrOutput)
}

func (o Apiv1UserSettingColorThemeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1UserSettingColorThemeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1UserSettingColorTheme) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1UserSettingColorThemeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1UserSettingColorThemeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1UserSettingColorTheme) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1UserSettingColorThemePtrOutput struct{ *pulumi.OutputState }

func (Apiv1UserSettingColorThemePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1UserSettingColorTheme)(nil)).Elem()
}

func (o Apiv1UserSettingColorThemePtrOutput) ToApiv1UserSettingColorThemePtrOutput() Apiv1UserSettingColorThemePtrOutput {
	return o
}

func (o Apiv1UserSettingColorThemePtrOutput) ToApiv1UserSettingColorThemePtrOutputWithContext(ctx context.Context) Apiv1UserSettingColorThemePtrOutput {
	return o
}

func (o Apiv1UserSettingColorThemePtrOutput) Elem() Apiv1UserSettingColorThemeOutput {
	return o.ApplyT(func(v *Apiv1UserSettingColorTheme) Apiv1UserSettingColorTheme {
		if v != nil {
			return *v
		}
		var ret Apiv1UserSettingColorTheme
		return ret
	}).(Apiv1UserSettingColorThemeOutput)
}

func (o Apiv1UserSettingColorThemePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1UserSettingColorThemePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1UserSettingColorTheme) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1UserSettingLocale string

const (
	Apiv1UserSettingLocaleLocaleUnspecified = Apiv1UserSettingLocale("LOCALE_UNSPECIFIED")
	Apiv1UserSettingLocaleLocaleEn          = Apiv1UserSettingLocale("LOCALE_EN")
	Apiv1UserSettingLocaleLocaleZh          = Apiv1UserSettingLocale("LOCALE_ZH")
	Apiv1UserSettingLocaleLocaleFr          = Apiv1UserSettingLocale("LOCALE_FR")
)

type Apiv1UserSettingLocaleOutput struct{ *pulumi.OutputState }

func (Apiv1UserSettingLocaleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1UserSettingLocale)(nil)).Elem()
}

func (o Apiv1UserSettingLocaleOutput) ToApiv1UserSettingLocaleOutput() Apiv1UserSettingLocaleOutput {
	return o
}

func (o Apiv1UserSettingLocaleOutput) ToApiv1UserSettingLocaleOutputWithContext(ctx context.Context) Apiv1UserSettingLocaleOutput {
	return o
}

func (o Apiv1UserSettingLocaleOutput) ToApiv1UserSettingLocalePtrOutput() Apiv1UserSettingLocalePtrOutput {
	return o.ToApiv1UserSettingLocalePtrOutputWithContext(context.Background())
}

func (o Apiv1UserSettingLocaleOutput) ToApiv1UserSettingLocalePtrOutputWithContext(ctx context.Context) Apiv1UserSettingLocalePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1UserSettingLocale) *Apiv1UserSettingLocale {
		return &v
	}).(Apiv1UserSettingLocalePtrOutput)
}

func (o Apiv1UserSettingLocaleOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1UserSettingLocaleOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1UserSettingLocale) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1UserSettingLocaleOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1UserSettingLocaleOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1UserSettingLocale) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1UserSettingLocalePtrOutput struct{ *pulumi.OutputState }

func (Apiv1UserSettingLocalePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1UserSettingLocale)(nil)).Elem()
}

func (o Apiv1UserSettingLocalePtrOutput) ToApiv1UserSettingLocalePtrOutput() Apiv1UserSettingLocalePtrOutput {
	return o
}

func (o Apiv1UserSettingLocalePtrOutput) ToApiv1UserSettingLocalePtrOutputWithContext(ctx context.Context) Apiv1UserSettingLocalePtrOutput {
	return o
}

func (o Apiv1UserSettingLocalePtrOutput) Elem() Apiv1UserSettingLocaleOutput {
	return o.ApplyT(func(v *Apiv1UserSettingLocale) Apiv1UserSettingLocale {
		if v != nil {
			return *v
		}
		var ret Apiv1UserSettingLocale
		return ret
	}).(Apiv1UserSettingLocaleOutput)
}

func (o Apiv1UserSettingLocalePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1UserSettingLocalePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1UserSettingLocale) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1WorkspaceSettingDefaultVisibility string

const (
	Apiv1WorkspaceSettingDefaultVisibilityVisibilityUnspecified = Apiv1WorkspaceSettingDefaultVisibility("VISIBILITY_UNSPECIFIED")
	Apiv1WorkspaceSettingDefaultVisibilityPrivate               = Apiv1WorkspaceSettingDefaultVisibility("PRIVATE")
	Apiv1WorkspaceSettingDefaultVisibilityWorkspace             = Apiv1WorkspaceSettingDefaultVisibility("WORKSPACE")
	Apiv1WorkspaceSettingDefaultVisibilityPublic                = Apiv1WorkspaceSettingDefaultVisibility("PUBLIC")
)

type Apiv1WorkspaceSettingDefaultVisibilityOutput struct{ *pulumi.OutputState }

func (Apiv1WorkspaceSettingDefaultVisibilityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Apiv1WorkspaceSettingDefaultVisibility)(nil)).Elem()
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToApiv1WorkspaceSettingDefaultVisibilityOutput() Apiv1WorkspaceSettingDefaultVisibilityOutput {
	return o
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToApiv1WorkspaceSettingDefaultVisibilityOutputWithContext(ctx context.Context) Apiv1WorkspaceSettingDefaultVisibilityOutput {
	return o
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToApiv1WorkspaceSettingDefaultVisibilityPtrOutput() Apiv1WorkspaceSettingDefaultVisibilityPtrOutput {
	return o.ToApiv1WorkspaceSettingDefaultVisibilityPtrOutputWithContext(context.Background())
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToApiv1WorkspaceSettingDefaultVisibilityPtrOutputWithContext(ctx context.Context) Apiv1WorkspaceSettingDefaultVisibilityPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Apiv1WorkspaceSettingDefaultVisibility) *Apiv1WorkspaceSettingDefaultVisibility {
		return &v
	}).(Apiv1WorkspaceSettingDefaultVisibilityPtrOutput)
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1WorkspaceSettingDefaultVisibility) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1WorkspaceSettingDefaultVisibilityOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Apiv1WorkspaceSettingDefaultVisibility) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Apiv1WorkspaceSettingDefaultVisibilityPtrOutput struct{ *pulumi.OutputState }

func (Apiv1WorkspaceSettingDefaultVisibilityPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Apiv1WorkspaceSettingDefaultVisibility)(nil)).Elem()
}

func (o Apiv1WorkspaceSettingDefaultVisibilityPtrOutput) ToApiv1WorkspaceSettingDefaultVisibilityPtrOutput() Apiv1WorkspaceSettingDefaultVisibilityPtrOutput {
	return o
}

func (o Apiv1WorkspaceSettingDefaultVisibilityPtrOutput) ToApiv1WorkspaceSettingDefaultVisibilityPtrOutputWithContext(ctx context.Context) Apiv1WorkspaceSettingDefaultVisibilityPtrOutput {
	return o
}

func (o Apiv1WorkspaceSettingDefaultVisibilityPtrOutput) Elem() Apiv1WorkspaceSettingDefaultVisibilityOutput {
	return o.ApplyT(func(v *Apiv1WorkspaceSettingDefaultVisibility) Apiv1WorkspaceSettingDefaultVisibility {
		if v != nil {
			return *v
		}
		var ret Apiv1WorkspaceSettingDefaultVisibility
		return ret
	}).(Apiv1WorkspaceSettingDefaultVisibilityOutput)
}

func (o Apiv1WorkspaceSettingDefaultVisibilityPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o Apiv1WorkspaceSettingDefaultVisibilityPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Apiv1WorkspaceSettingDefaultVisibility) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Role string

const (
	RoleRoleUnspecified = Role("ROLE_UNSPECIFIED")
	RoleAdmin           = Role("ADMIN")
	RoleUser            = Role("USER")
)

func (Role) ElementType() reflect.Type {
	return reflect.TypeOf((*Role)(nil)).Elem()
}

func (e Role) ToRoleOutput() RoleOutput {
	return pulumi.ToOutput(e).(RoleOutput)
}

func (e Role) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RoleOutput)
}

func (e Role) ToRolePtrOutput() RolePtrOutput {
	return e.ToRolePtrOutputWithContext(context.Background())
}

func (e Role) ToRolePtrOutputWithContext(ctx context.Context) RolePtrOutput {
	return Role(e).ToRoleOutputWithContext(ctx).ToRolePtrOutputWithContext(ctx)
}

func (e Role) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e Role) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e Role) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e Role) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RoleOutput struct{ *pulumi.OutputState }

func (RoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Role)(nil)).Elem()
}

func (o RoleOutput) ToRoleOutput() RoleOutput {
	return o
}

func (o RoleOutput) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return o
}

func (o RoleOutput) ToRolePtrOutput() RolePtrOutput {
	return o.ToRolePtrOutputWithContext(context.Background())
}

func (o RoleOutput) ToRolePtrOutputWithContext(ctx context.Context) RolePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Role) *Role {
		return &v
	}).(RolePtrOutput)
}

func (o RoleOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RoleOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Role) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RoleOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RoleOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Role) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RolePtrOutput struct{ *pulumi.OutputState }

func (RolePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (o RolePtrOutput) ToRolePtrOutput() RolePtrOutput {
	return o
}

func (o RolePtrOutput) ToRolePtrOutputWithContext(ctx context.Context) RolePtrOutput {
	return o
}

func (o RolePtrOutput) Elem() RoleOutput {
	return o.ApplyT(func(v *Role) Role {
		if v != nil {
			return *v
		}
		var ret Role
		return ret
	}).(RoleOutput)
}

func (o RolePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RolePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Role) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RoleInput is an input type that accepts values of the Role enum
// A concrete instance of `RoleInput` can be one of the following:
//
//	RoleRoleUnspecified
//	RoleAdmin
//	RoleUser
type RoleInput interface {
	pulumi.Input

	ToRoleOutput() RoleOutput
	ToRoleOutputWithContext(context.Context) RoleOutput
}

var rolePtrType = reflect.TypeOf((**Role)(nil)).Elem()

type RolePtrInput interface {
	pulumi.Input

	ToRolePtrOutput() RolePtrOutput
	ToRolePtrOutputWithContext(context.Context) RolePtrOutput
}

type rolePtr string

func RolePtr(v string) RolePtrInput {
	return (*rolePtr)(&v)
}

func (*rolePtr) ElementType() reflect.Type {
	return rolePtrType
}

func (in *rolePtr) ToRolePtrOutput() RolePtrOutput {
	return pulumi.ToOutput(in).(RolePtrOutput)
}

func (in *rolePtr) ToRolePtrOutputWithContext(ctx context.Context) RolePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RolePtrOutput)
}

type RowStatus string

const (
	RowStatusRowStatusUnspecified = RowStatus("ROW_STATUS_UNSPECIFIED")
	RowStatusNormal               = RowStatus("NORMAL")
	RowStatusArchived             = RowStatus("ARCHIVED")
)

func (RowStatus) ElementType() reflect.Type {
	return reflect.TypeOf((*RowStatus)(nil)).Elem()
}

func (e RowStatus) ToRowStatusOutput() RowStatusOutput {
	return pulumi.ToOutput(e).(RowStatusOutput)
}

func (e RowStatus) ToRowStatusOutputWithContext(ctx context.Context) RowStatusOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RowStatusOutput)
}

func (e RowStatus) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return e.ToRowStatusPtrOutputWithContext(context.Background())
}

func (e RowStatus) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return RowStatus(e).ToRowStatusOutputWithContext(ctx).ToRowStatusPtrOutputWithContext(ctx)
}

func (e RowStatus) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e RowStatus) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e RowStatus) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e RowStatus) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RowStatusOutput struct{ *pulumi.OutputState }

func (RowStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RowStatus)(nil)).Elem()
}

func (o RowStatusOutput) ToRowStatusOutput() RowStatusOutput {
	return o
}

func (o RowStatusOutput) ToRowStatusOutputWithContext(ctx context.Context) RowStatusOutput {
	return o
}

func (o RowStatusOutput) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return o.ToRowStatusPtrOutputWithContext(context.Background())
}

func (o RowStatusOutput) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RowStatus) *RowStatus {
		return &v
	}).(RowStatusPtrOutput)
}

func (o RowStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RowStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RowStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RowStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RowStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RowStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RowStatusPtrOutput struct{ *pulumi.OutputState }

func (RowStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RowStatus)(nil)).Elem()
}

func (o RowStatusPtrOutput) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return o
}

func (o RowStatusPtrOutput) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return o
}

func (o RowStatusPtrOutput) Elem() RowStatusOutput {
	return o.ApplyT(func(v *RowStatus) RowStatus {
		if v != nil {
			return *v
		}
		var ret RowStatus
		return ret
	}).(RowStatusOutput)
}

func (o RowStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RowStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RowStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RowStatusInput is an input type that accepts values of the RowStatus enum
// A concrete instance of `RowStatusInput` can be one of the following:
//
//	RowStatusRowStatusUnspecified
//	RowStatusNormal
//	RowStatusArchived
type RowStatusInput interface {
	pulumi.Input

	ToRowStatusOutput() RowStatusOutput
	ToRowStatusOutputWithContext(context.Context) RowStatusOutput
}

var rowStatusPtrType = reflect.TypeOf((**RowStatus)(nil)).Elem()

type RowStatusPtrInput interface {
	pulumi.Input

	ToRowStatusPtrOutput() RowStatusPtrOutput
	ToRowStatusPtrOutputWithContext(context.Context) RowStatusPtrOutput
}

type rowStatusPtr string

func RowStatusPtr(v string) RowStatusPtrInput {
	return (*rowStatusPtr)(&v)
}

func (*rowStatusPtr) ElementType() reflect.Type {
	return rowStatusPtrType
}

func (in *rowStatusPtr) ToRowStatusPtrOutput() RowStatusPtrOutput {
	return pulumi.ToOutput(in).(RowStatusPtrOutput)
}

func (in *rowStatusPtr) ToRowStatusPtrOutputWithContext(ctx context.Context) RowStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RowStatusPtrOutput)
}

type V1UserRole string

const (
	V1UserRoleRoleUnspecified = V1UserRole("ROLE_UNSPECIFIED")
	V1UserRoleAdmin           = V1UserRole("ADMIN")
	V1UserRoleUser            = V1UserRole("USER")
)

type V1UserRoleOutput struct{ *pulumi.OutputState }

func (V1UserRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1UserRole)(nil)).Elem()
}

func (o V1UserRoleOutput) ToV1UserRoleOutput() V1UserRoleOutput {
	return o
}

func (o V1UserRoleOutput) ToV1UserRoleOutputWithContext(ctx context.Context) V1UserRoleOutput {
	return o
}

func (o V1UserRoleOutput) ToV1UserRolePtrOutput() V1UserRolePtrOutput {
	return o.ToV1UserRolePtrOutputWithContext(context.Background())
}

func (o V1UserRoleOutput) ToV1UserRolePtrOutputWithContext(ctx context.Context) V1UserRolePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v V1UserRole) *V1UserRole {
		return &v
	}).(V1UserRolePtrOutput)
}

func (o V1UserRoleOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o V1UserRoleOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e V1UserRole) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o V1UserRoleOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o V1UserRoleOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e V1UserRole) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type V1UserRolePtrOutput struct{ *pulumi.OutputState }

func (V1UserRolePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**V1UserRole)(nil)).Elem()
}

func (o V1UserRolePtrOutput) ToV1UserRolePtrOutput() V1UserRolePtrOutput {
	return o
}

func (o V1UserRolePtrOutput) ToV1UserRolePtrOutputWithContext(ctx context.Context) V1UserRolePtrOutput {
	return o
}

func (o V1UserRolePtrOutput) Elem() V1UserRoleOutput {
	return o.ApplyT(func(v *V1UserRole) V1UserRole {
		if v != nil {
			return *v
		}
		var ret V1UserRole
		return ret
	}).(V1UserRoleOutput)
}

func (o V1UserRolePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o V1UserRolePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *V1UserRole) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type V1UserRowStatus string

const (
	V1UserRowStatusRowStatusUnspecified = V1UserRowStatus("ROW_STATUS_UNSPECIFIED")
	V1UserRowStatusNormal               = V1UserRowStatus("NORMAL")
	V1UserRowStatusArchived             = V1UserRowStatus("ARCHIVED")
)

type V1UserRowStatusOutput struct{ *pulumi.OutputState }

func (V1UserRowStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1UserRowStatus)(nil)).Elem()
}

func (o V1UserRowStatusOutput) ToV1UserRowStatusOutput() V1UserRowStatusOutput {
	return o
}

func (o V1UserRowStatusOutput) ToV1UserRowStatusOutputWithContext(ctx context.Context) V1UserRowStatusOutput {
	return o
}

func (o V1UserRowStatusOutput) ToV1UserRowStatusPtrOutput() V1UserRowStatusPtrOutput {
	return o.ToV1UserRowStatusPtrOutputWithContext(context.Background())
}

func (o V1UserRowStatusOutput) ToV1UserRowStatusPtrOutputWithContext(ctx context.Context) V1UserRowStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v V1UserRowStatus) *V1UserRowStatus {
		return &v
	}).(V1UserRowStatusPtrOutput)
}

func (o V1UserRowStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o V1UserRowStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e V1UserRowStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o V1UserRowStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o V1UserRowStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e V1UserRowStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type V1UserRowStatusPtrOutput struct{ *pulumi.OutputState }

func (V1UserRowStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**V1UserRowStatus)(nil)).Elem()
}

func (o V1UserRowStatusPtrOutput) ToV1UserRowStatusPtrOutput() V1UserRowStatusPtrOutput {
	return o
}

func (o V1UserRowStatusPtrOutput) ToV1UserRowStatusPtrOutputWithContext(ctx context.Context) V1UserRowStatusPtrOutput {
	return o
}

func (o V1UserRowStatusPtrOutput) Elem() V1UserRowStatusOutput {
	return o.ApplyT(func(v *V1UserRowStatus) V1UserRowStatus {
		if v != nil {
			return *v
		}
		var ret V1UserRowStatus
		return ret
	}).(V1UserRowStatusOutput)
}

func (o V1UserRowStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o V1UserRowStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *V1UserRowStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type V1WorkspaceProfilePlan string

const (
	V1WorkspaceProfilePlanPlanTypeUnspecified = V1WorkspaceProfilePlan("PLAN_TYPE_UNSPECIFIED")
	V1WorkspaceProfilePlanFree                = V1WorkspaceProfilePlan("FREE")
	V1WorkspaceProfilePlanPro                 = V1WorkspaceProfilePlan("PRO")
)

type V1WorkspaceProfilePlanOutput struct{ *pulumi.OutputState }

func (V1WorkspaceProfilePlanOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*V1WorkspaceProfilePlan)(nil)).Elem()
}

func (o V1WorkspaceProfilePlanOutput) ToV1WorkspaceProfilePlanOutput() V1WorkspaceProfilePlanOutput {
	return o
}

func (o V1WorkspaceProfilePlanOutput) ToV1WorkspaceProfilePlanOutputWithContext(ctx context.Context) V1WorkspaceProfilePlanOutput {
	return o
}

func (o V1WorkspaceProfilePlanOutput) ToV1WorkspaceProfilePlanPtrOutput() V1WorkspaceProfilePlanPtrOutput {
	return o.ToV1WorkspaceProfilePlanPtrOutputWithContext(context.Background())
}

func (o V1WorkspaceProfilePlanOutput) ToV1WorkspaceProfilePlanPtrOutputWithContext(ctx context.Context) V1WorkspaceProfilePlanPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v V1WorkspaceProfilePlan) *V1WorkspaceProfilePlan {
		return &v
	}).(V1WorkspaceProfilePlanPtrOutput)
}

func (o V1WorkspaceProfilePlanOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o V1WorkspaceProfilePlanOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e V1WorkspaceProfilePlan) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o V1WorkspaceProfilePlanOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o V1WorkspaceProfilePlanOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e V1WorkspaceProfilePlan) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type V1WorkspaceProfilePlanPtrOutput struct{ *pulumi.OutputState }

func (V1WorkspaceProfilePlanPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**V1WorkspaceProfilePlan)(nil)).Elem()
}

func (o V1WorkspaceProfilePlanPtrOutput) ToV1WorkspaceProfilePlanPtrOutput() V1WorkspaceProfilePlanPtrOutput {
	return o
}

func (o V1WorkspaceProfilePlanPtrOutput) ToV1WorkspaceProfilePlanPtrOutputWithContext(ctx context.Context) V1WorkspaceProfilePlanPtrOutput {
	return o
}

func (o V1WorkspaceProfilePlanPtrOutput) Elem() V1WorkspaceProfilePlanOutput {
	return o.ApplyT(func(v *V1WorkspaceProfilePlan) V1WorkspaceProfilePlan {
		if v != nil {
			return *v
		}
		var ret V1WorkspaceProfilePlan
		return ret
	}).(V1WorkspaceProfilePlanOutput)
}

func (o V1WorkspaceProfilePlanPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o V1WorkspaceProfilePlanPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *V1WorkspaceProfilePlan) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type Visibility string

const (
	VisibilityVisibilityUnspecified = Visibility("VISIBILITY_UNSPECIFIED")
	VisibilityPrivate               = Visibility("PRIVATE")
	VisibilityWorkspace             = Visibility("WORKSPACE")
	VisibilityPublic                = Visibility("PUBLIC")
)

func (Visibility) ElementType() reflect.Type {
	return reflect.TypeOf((*Visibility)(nil)).Elem()
}

func (e Visibility) ToVisibilityOutput() VisibilityOutput {
	return pulumi.ToOutput(e).(VisibilityOutput)
}

func (e Visibility) ToVisibilityOutputWithContext(ctx context.Context) VisibilityOutput {
	return pulumi.ToOutputWithContext(ctx, e).(VisibilityOutput)
}

func (e Visibility) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return e.ToVisibilityPtrOutputWithContext(context.Background())
}

func (e Visibility) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return Visibility(e).ToVisibilityOutputWithContext(ctx).ToVisibilityPtrOutputWithContext(ctx)
}

func (e Visibility) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e Visibility) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e Visibility) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e Visibility) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type VisibilityOutput struct{ *pulumi.OutputState }

func (VisibilityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Visibility)(nil)).Elem()
}

func (o VisibilityOutput) ToVisibilityOutput() VisibilityOutput {
	return o
}

func (o VisibilityOutput) ToVisibilityOutputWithContext(ctx context.Context) VisibilityOutput {
	return o
}

func (o VisibilityOutput) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return o.ToVisibilityPtrOutputWithContext(context.Background())
}

func (o VisibilityOutput) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Visibility) *Visibility {
		return &v
	}).(VisibilityPtrOutput)
}

func (o VisibilityOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o VisibilityOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Visibility) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o VisibilityOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o VisibilityOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Visibility) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type VisibilityPtrOutput struct{ *pulumi.OutputState }

func (VisibilityPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Visibility)(nil)).Elem()
}

func (o VisibilityPtrOutput) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return o
}

func (o VisibilityPtrOutput) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return o
}

func (o VisibilityPtrOutput) Elem() VisibilityOutput {
	return o.ApplyT(func(v *Visibility) Visibility {
		if v != nil {
			return *v
		}
		var ret Visibility
		return ret
	}).(VisibilityOutput)
}

func (o VisibilityPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o VisibilityPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Visibility) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// VisibilityInput is an input type that accepts values of the Visibility enum
// A concrete instance of `VisibilityInput` can be one of the following:
//
//	VisibilityVisibilityUnspecified
//	VisibilityPrivate
//	VisibilityWorkspace
//	VisibilityPublic
type VisibilityInput interface {
	pulumi.Input

	ToVisibilityOutput() VisibilityOutput
	ToVisibilityOutputWithContext(context.Context) VisibilityOutput
}

var visibilityPtrType = reflect.TypeOf((**Visibility)(nil)).Elem()

type VisibilityPtrInput interface {
	pulumi.Input

	ToVisibilityPtrOutput() VisibilityPtrOutput
	ToVisibilityPtrOutputWithContext(context.Context) VisibilityPtrOutput
}

type visibilityPtr string

func VisibilityPtr(v string) VisibilityPtrInput {
	return (*visibilityPtr)(&v)
}

func (*visibilityPtr) ElementType() reflect.Type {
	return visibilityPtrType
}

func (in *visibilityPtr) ToVisibilityPtrOutput() VisibilityPtrOutput {
	return pulumi.ToOutput(in).(VisibilityPtrOutput)
}

func (in *visibilityPtr) ToVisibilityPtrOutputWithContext(ctx context.Context) VisibilityPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(VisibilityPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RoleInput)(nil)).Elem(), Role("ROLE_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*RolePtrInput)(nil)).Elem(), Role("ROLE_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*RowStatusInput)(nil)).Elem(), RowStatus("ROW_STATUS_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*RowStatusPtrInput)(nil)).Elem(), RowStatus("ROW_STATUS_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*VisibilityInput)(nil)).Elem(), Visibility("VISIBILITY_UNSPECIFIED"))
	pulumi.RegisterInputType(reflect.TypeOf((*VisibilityPtrInput)(nil)).Elem(), Visibility("VISIBILITY_UNSPECIFIED"))
	pulumi.RegisterOutputType(Apiv1CollectionVisibilityOutput{})
	pulumi.RegisterOutputType(Apiv1CollectionVisibilityPtrOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutRowStatusOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutRowStatusPtrOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutVisibilityOutput{})
	pulumi.RegisterOutputType(Apiv1ShortcutVisibilityPtrOutput{})
	pulumi.RegisterOutputType(Apiv1UserSettingColorThemeOutput{})
	pulumi.RegisterOutputType(Apiv1UserSettingColorThemePtrOutput{})
	pulumi.RegisterOutputType(Apiv1UserSettingLocaleOutput{})
	pulumi.RegisterOutputType(Apiv1UserSettingLocalePtrOutput{})
	pulumi.RegisterOutputType(Apiv1WorkspaceSettingDefaultVisibilityOutput{})
	pulumi.RegisterOutputType(Apiv1WorkspaceSettingDefaultVisibilityPtrOutput{})
	pulumi.RegisterOutputType(RoleOutput{})
	pulumi.RegisterOutputType(RolePtrOutput{})
	pulumi.RegisterOutputType(RowStatusOutput{})
	pulumi.RegisterOutputType(RowStatusPtrOutput{})
	pulumi.RegisterOutputType(V1UserRoleOutput{})
	pulumi.RegisterOutputType(V1UserRolePtrOutput{})
	pulumi.RegisterOutputType(V1UserRowStatusOutput{})
	pulumi.RegisterOutputType(V1UserRowStatusPtrOutput{})
	pulumi.RegisterOutputType(V1WorkspaceProfilePlanOutput{})
	pulumi.RegisterOutputType(V1WorkspaceProfilePlanPtrOutput{})
	pulumi.RegisterOutputType(VisibilityOutput{})
	pulumi.RegisterOutputType(VisibilityPtrOutput{})
}
