# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'V1SubscriptionPlan',
]


class V1SubscriptionPlan(str, Enum):
    PLAN_TYPE_UNSPECIFIED = "PLAN_TYPE_UNSPECIFIED"
    FREE = "FREE"
    PRO = "PRO"
