# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetSubscriptionServiceSubscriptionResult',
    'AwaitableGetSubscriptionServiceSubscriptionResult',
    'get_subscription_service_subscription',
    'get_subscription_service_subscription_output',
]

@pulumi.output_type
class GetSubscriptionServiceSubscriptionResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.V1GetSubscriptionResponse':
        return pulumi.get(self, "items")


class AwaitableGetSubscriptionServiceSubscriptionResult(GetSubscriptionServiceSubscriptionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSubscriptionServiceSubscriptionResult(
            items=self.items)


def get_subscription_service_subscription(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSubscriptionServiceSubscriptionResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('slash:subscription/v1:getSubscriptionServiceSubscription', __args__, opts=opts, typ=GetSubscriptionServiceSubscriptionResult).value

    return AwaitableGetSubscriptionServiceSubscriptionResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(get_subscription_service_subscription)
def get_subscription_service_subscription_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetSubscriptionServiceSubscriptionResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
