// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Apiv1ShortcutRowStatus = {
    RowStatusUnspecified: "ROW_STATUS_UNSPECIFIED",
    Normal: "NORMAL",
    Archived: "ARCHIVED",
} as const;

export type Apiv1ShortcutRowStatus = (typeof Apiv1ShortcutRowStatus)[keyof typeof Apiv1ShortcutRowStatus];

export const Apiv1ShortcutVisibility = {
    VisibilityUnspecified: "VISIBILITY_UNSPECIFIED",
    Private: "PRIVATE",
    Workspace: "WORKSPACE",
    Public: "PUBLIC",
} as const;

export type Apiv1ShortcutVisibility = (typeof Apiv1ShortcutVisibility)[keyof typeof Apiv1ShortcutVisibility];

export const RowStatus = {
    RowStatusUnspecified: "ROW_STATUS_UNSPECIFIED",
    Normal: "NORMAL",
    Archived: "ARCHIVED",
} as const;

export type RowStatus = (typeof RowStatus)[keyof typeof RowStatus];

export const Visibility = {
    VisibilityUnspecified: "VISIBILITY_UNSPECIFIED",
    Private: "PRIVATE",
    Workspace: "WORKSPACE",
    Public: "PUBLIC",
} as const;

export type Visibility = (typeof Visibility)[keyof typeof Visibility];
