// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Apiv1CollectionVisibility = {
    VisibilityUnspecified: "VISIBILITY_UNSPECIFIED",
    Private: "PRIVATE",
    Workspace: "WORKSPACE",
    Public: "PUBLIC",
} as const;

export type Apiv1CollectionVisibility = (typeof Apiv1CollectionVisibility)[keyof typeof Apiv1CollectionVisibility];

export const Apiv1ShortcutRowStatus = {
    RowStatusUnspecified: "ROW_STATUS_UNSPECIFIED",
    Normal: "NORMAL",
    Archived: "ARCHIVED",
} as const;

export type Apiv1ShortcutRowStatus = (typeof Apiv1ShortcutRowStatus)[keyof typeof Apiv1ShortcutRowStatus];

export const Apiv1ShortcutVisibility = {
    VisibilityUnspecified: "VISIBILITY_UNSPECIFIED",
    Private: "PRIVATE",
    Workspace: "WORKSPACE",
    Public: "PUBLIC",
} as const;

export type Apiv1ShortcutVisibility = (typeof Apiv1ShortcutVisibility)[keyof typeof Apiv1ShortcutVisibility];

export const Apiv1UserSettingColorTheme = {
    ColorThemeUnspecified: "COLOR_THEME_UNSPECIFIED",
    ColorThemeSystem: "COLOR_THEME_SYSTEM",
    ColorThemeLight: "COLOR_THEME_LIGHT",
    ColorThemeDark: "COLOR_THEME_DARK",
} as const;

export type Apiv1UserSettingColorTheme = (typeof Apiv1UserSettingColorTheme)[keyof typeof Apiv1UserSettingColorTheme];

export const Apiv1UserSettingLocale = {
    LocaleUnspecified: "LOCALE_UNSPECIFIED",
    LocaleEn: "LOCALE_EN",
    LocaleZh: "LOCALE_ZH",
    LocaleFr: "LOCALE_FR",
} as const;

export type Apiv1UserSettingLocale = (typeof Apiv1UserSettingLocale)[keyof typeof Apiv1UserSettingLocale];

export const Apiv1WorkspaceSettingDefaultVisibility = {
    VisibilityUnspecified: "VISIBILITY_UNSPECIFIED",
    Private: "PRIVATE",
    Workspace: "WORKSPACE",
    Public: "PUBLIC",
} as const;

export type Apiv1WorkspaceSettingDefaultVisibility = (typeof Apiv1WorkspaceSettingDefaultVisibility)[keyof typeof Apiv1WorkspaceSettingDefaultVisibility];

export const Role = {
    RoleUnspecified: "ROLE_UNSPECIFIED",
    Admin: "ADMIN",
    User: "USER",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const RowStatus = {
    RowStatusUnspecified: "ROW_STATUS_UNSPECIFIED",
    Normal: "NORMAL",
    Archived: "ARCHIVED",
} as const;

export type RowStatus = (typeof RowStatus)[keyof typeof RowStatus];

export const V1UserRole = {
    RoleUnspecified: "ROLE_UNSPECIFIED",
    Admin: "ADMIN",
    User: "USER",
} as const;

export type V1UserRole = (typeof V1UserRole)[keyof typeof V1UserRole];

export const V1UserRowStatus = {
    RowStatusUnspecified: "ROW_STATUS_UNSPECIFIED",
    Normal: "NORMAL",
    Archived: "ARCHIVED",
} as const;

export type V1UserRowStatus = (typeof V1UserRowStatus)[keyof typeof V1UserRowStatus];

export const V1WorkspaceProfilePlan = {
    PlanTypeUnspecified: "PLAN_TYPE_UNSPECIFIED",
    Free: "FREE",
    Pro: "PRO",
} as const;

export type V1WorkspaceProfilePlan = (typeof V1WorkspaceProfilePlan)[keyof typeof V1WorkspaceProfilePlan];

export const Visibility = {
    VisibilityUnspecified: "VISIBILITY_UNSPECIFIED",
    Private: "PRIVATE",
    Workspace: "WORKSPACE",
    Public: "PUBLIC",
} as const;

export type Visibility = (typeof Visibility)[keyof typeof Visibility];
