# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_slash.api as __api
    api = __api
    import pulumi_slash.config as __config
    config = __config
    import pulumi_slash.subscription as __subscription
    subscription = __subscription
else:
    api = _utilities.lazy_import('pulumi_slash.api')
    config = _utilities.lazy_import('pulumi_slash.config')
    subscription = _utilities.lazy_import('pulumi_slash.subscription')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "slash",
  "mod": "api",
  "fqn": "pulumi_slash.api",
  "classes": {
   "slash:api:CollectionServiceCollection": "CollectionServiceCollection",
   "slash:api:ShortcutServiceShortcut": "ShortcutServiceShortcut",
   "slash:api:UserServiceUser": "UserServiceUser",
   "slash:api:UserServiceUserAccessToken": "UserServiceUserAccessToken"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "slash",
  "token": "pulumi:providers:slash",
  "fqn": "pulumi_slash",
  "class": "Provider"
 }
]
"""
)
