// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const V1SubscriptionPlan = {
    PlanTypeUnspecified: "PLAN_TYPE_UNSPECIFIED",
    Free: "FREE",
    Pro: "PRO",
} as const;

export type V1SubscriptionPlan = (typeof V1SubscriptionPlan)[keyof typeof V1SubscriptionPlan];
