// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import * as utilities from "../utilities";

export namespace api {
    export interface Apiv1OpenGraphMetadataArgs {
        description?: pulumi.Input<string>;
        image?: pulumi.Input<string>;
        title?: pulumi.Input<string>;
    }

}

export namespace subscription {
    export namespace v1 {
    }
}
