// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import * as utilities from "../utilities";

export namespace api {
    export interface Apiv1OpenGraphMetadata {
        description?: string;
        image?: string;
        title?: string;
    }

    export interface Apiv1Shortcut {
        createdTime?: string;
        creatorId?: number;
        description?: string;
        id?: number;
        link?: string;
        name?: string;
        ogMetadata?: outputs.api.Apiv1OpenGraphMetadata;
        rowStatus?: enums.api.Apiv1ShortcutRowStatus;
        tags?: string[];
        title?: string;
        updatedTime?: string;
        viewCount?: number;
        visibility?: enums.api.Apiv1ShortcutVisibility;
    }
    /**
     * apiv1ShortcutProvideDefaults sets the appropriate defaults for Apiv1Shortcut
     */
    export function apiv1ShortcutProvideDefaults(val: Apiv1Shortcut): Apiv1Shortcut {
        return {
            ...val,
            rowStatus: (val.rowStatus) ?? "ROW_STATUS_UNSPECIFIED",
            visibility: (val.visibility) ?? "VISIBILITY_UNSPECIFIED",
        };
    }

    export interface V1GetShortcutResponse {
        shortcut?: outputs.api.Apiv1Shortcut;
    }
    /**
     * v1getShortcutResponseProvideDefaults sets the appropriate defaults for V1GetShortcutResponse
     */
    export function v1getShortcutResponseProvideDefaults(val: V1GetShortcutResponse): V1GetShortcutResponse {
        return {
            ...val,
            shortcut: (val.shortcut ? outputs.api.apiv1ShortcutProvideDefaults(val.shortcut) : undefined),
        };
    }

    export interface V1ListShortcutsResponse {
        shortcuts?: outputs.api.Apiv1Shortcut[];
    }

}
