// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import * as utilities from "../utilities";

export namespace api {
    export interface Apiv1AutoBackupWorkspaceSetting {
        /**
         * The cron expression for auto backup.
         * For example, "0 0 0 * * *" means backup at 00:00:00 every day.
         * See https://en.wikipedia.org/wiki/Cron for more details.
         */
        cronExpression?: string;
        /**
         * Whether auto backup is enabled.
         */
        enabled?: boolean;
        /**
         * The maximum number of backups to keep.
         */
        maxKeep?: number;
    }

    export interface Apiv1Collection {
        createdTime?: string;
        creatorId?: number;
        description?: string;
        id?: number;
        ids?: number[];
        name?: string;
        title?: string;
        updatedTime?: string;
        visibility?: enums.api.Apiv1CollectionVisibility;
    }
    /**
     * apiv1CollectionProvideDefaults sets the appropriate defaults for Apiv1Collection
     */
    export function apiv1CollectionProvideDefaults(val: Apiv1Collection): Apiv1Collection {
        return {
            ...val,
            visibility: (val.visibility) ?? "VISIBILITY_UNSPECIFIED",
        };
    }

    export interface Apiv1OpenGraphMetadata {
        description?: string;
        image?: string;
        title?: string;
    }

    export interface Apiv1Shortcut {
        createdTime?: string;
        creatorId?: number;
        description?: string;
        id?: number;
        link?: string;
        name?: string;
        ogMetadata?: outputs.api.Apiv1OpenGraphMetadata;
        rowStatus?: enums.api.Apiv1ShortcutRowStatus;
        tags?: string[];
        title?: string;
        updatedTime?: string;
        viewCount?: number;
        visibility?: enums.api.Apiv1ShortcutVisibility;
    }
    /**
     * apiv1ShortcutProvideDefaults sets the appropriate defaults for Apiv1Shortcut
     */
    export function apiv1ShortcutProvideDefaults(val: Apiv1Shortcut): Apiv1Shortcut {
        return {
            ...val,
            rowStatus: (val.rowStatus) ?? "ROW_STATUS_UNSPECIFIED",
            visibility: (val.visibility) ?? "VISIBILITY_UNSPECIFIED",
        };
    }

    export interface Apiv1UserSetting {
        colorTheme?: enums.api.Apiv1UserSettingColorTheme;
        /**
         * id is the user id.
         */
        id?: number;
        locale?: enums.api.Apiv1UserSettingLocale;
    }
    /**
     * apiv1UserSettingProvideDefaults sets the appropriate defaults for Apiv1UserSetting
     */
    export function apiv1UserSettingProvideDefaults(val: Apiv1UserSetting): Apiv1UserSetting {
        return {
            ...val,
            colorTheme: (val.colorTheme) ?? "COLOR_THEME_UNSPECIFIED",
            locale: (val.locale) ?? "LOCALE_UNSPECIFIED",
        };
    }

    export interface Apiv1WorkspaceSetting {
        autoBackup?: outputs.api.Apiv1AutoBackupWorkspaceSetting;
        /**
         * The custom script.
         */
        customScript?: string;
        /**
         * The custom style.
         */
        customStyle?: string;
        defaultVisibility?: enums.api.Apiv1WorkspaceSettingDefaultVisibility;
        /**
         * Whether to enable other users to sign up.
         */
        enableSignup?: boolean;
        /**
         * The url of custom favicon provider.
         */
        faviconProvider?: string;
        /**
         * The instance URL.
         */
        instanceUrl?: string;
        licenseKey?: string;
    }
    /**
     * apiv1WorkspaceSettingProvideDefaults sets the appropriate defaults for Apiv1WorkspaceSetting
     */
    export function apiv1WorkspaceSettingProvideDefaults(val: Apiv1WorkspaceSetting): Apiv1WorkspaceSetting {
        return {
            ...val,
            defaultVisibility: (val.defaultVisibility) ?? "VISIBILITY_UNSPECIFIED",
        };
    }

    export interface V1GetCollectionResponse {
        collection?: outputs.api.Apiv1Collection;
    }
    /**
     * v1getCollectionResponseProvideDefaults sets the appropriate defaults for V1GetCollectionResponse
     */
    export function v1getCollectionResponseProvideDefaults(val: V1GetCollectionResponse): V1GetCollectionResponse {
        return {
            ...val,
            collection: (val.collection ? outputs.api.apiv1CollectionProvideDefaults(val.collection) : undefined),
        };
    }

    export interface V1GetShortcutResponse {
        shortcut?: outputs.api.Apiv1Shortcut;
    }
    /**
     * v1getShortcutResponseProvideDefaults sets the appropriate defaults for V1GetShortcutResponse
     */
    export function v1getShortcutResponseProvideDefaults(val: V1GetShortcutResponse): V1GetShortcutResponse {
        return {
            ...val,
            shortcut: (val.shortcut ? outputs.api.apiv1ShortcutProvideDefaults(val.shortcut) : undefined),
        };
    }

    export interface V1GetUserResponse {
        user?: outputs.api.V1User;
    }
    /**
     * v1getUserResponseProvideDefaults sets the appropriate defaults for V1GetUserResponse
     */
    export function v1getUserResponseProvideDefaults(val: V1GetUserResponse): V1GetUserResponse {
        return {
            ...val,
            user: (val.user ? outputs.api.v1userProvideDefaults(val.user) : undefined),
        };
    }

    export interface V1GetUserSettingResponse {
        userSetting?: outputs.api.Apiv1UserSetting;
    }
    /**
     * v1getUserSettingResponseProvideDefaults sets the appropriate defaults for V1GetUserSettingResponse
     */
    export function v1getUserSettingResponseProvideDefaults(val: V1GetUserSettingResponse): V1GetUserSettingResponse {
        return {
            ...val,
            userSetting: (val.userSetting ? outputs.api.apiv1UserSettingProvideDefaults(val.userSetting) : undefined),
        };
    }

    export interface V1GetWorkspaceProfileResponse {
        profile?: outputs.api.V1WorkspaceProfile;
    }
    /**
     * v1getWorkspaceProfileResponseProvideDefaults sets the appropriate defaults for V1GetWorkspaceProfileResponse
     */
    export function v1getWorkspaceProfileResponseProvideDefaults(val: V1GetWorkspaceProfileResponse): V1GetWorkspaceProfileResponse {
        return {
            ...val,
            profile: (val.profile ? outputs.api.v1workspaceProfileProvideDefaults(val.profile) : undefined),
        };
    }

    export interface V1GetWorkspaceSettingResponse {
        setting?: outputs.api.Apiv1WorkspaceSetting;
    }
    /**
     * v1getWorkspaceSettingResponseProvideDefaults sets the appropriate defaults for V1GetWorkspaceSettingResponse
     */
    export function v1getWorkspaceSettingResponseProvideDefaults(val: V1GetWorkspaceSettingResponse): V1GetWorkspaceSettingResponse {
        return {
            ...val,
            setting: (val.setting ? outputs.api.apiv1WorkspaceSettingProvideDefaults(val.setting) : undefined),
        };
    }

    export interface V1ListCollectionsResponse {
        collections?: outputs.api.Apiv1Collection[];
    }

    export interface V1ListShortcutsResponse {
        shortcuts?: outputs.api.Apiv1Shortcut[];
    }

    export interface V1ListUserAccessTokensResponse {
        accessTokens?: outputs.api.V1UserAccessToken[];
    }

    export interface V1ListUsersResponse {
        users?: outputs.api.V1User[];
    }

    export interface V1User {
        createdTime?: string;
        email?: string;
        id?: number;
        nickname?: string;
        password?: string;
        role?: enums.api.V1UserRole;
        rowStatus?: enums.api.V1UserRowStatus;
        updatedTime?: string;
    }
    /**
     * v1userProvideDefaults sets the appropriate defaults for V1User
     */
    export function v1userProvideDefaults(val: V1User): V1User {
        return {
            ...val,
            role: (val.role) ?? "ROLE_UNSPECIFIED",
            rowStatus: (val.rowStatus) ?? "ROW_STATUS_UNSPECIFIED",
        };
    }

    export interface V1UserAccessToken {
        accessToken?: string;
        description?: string;
        expiresAt?: string;
        issuedAt?: string;
    }

    export interface V1WorkspaceProfile {
        /**
         * The custom script.
         */
        customScript?: string;
        /**
         * The custom style.
         */
        customStyle?: string;
        /**
         * Whether to enable other users to sign up.
         */
        enableSignup?: boolean;
        /**
         * The url of custom favicon provider.
         */
        faviconProvider?: string;
        /**
         * Current workspace mode: dev, prod.
         */
        mode?: string;
        owner?: string;
        plan?: enums.api.V1WorkspaceProfilePlan;
        /**
         * Current workspace version.
         */
        version?: string;
    }
    /**
     * v1workspaceProfileProvideDefaults sets the appropriate defaults for V1WorkspaceProfile
     */
    export function v1workspaceProfileProvideDefaults(val: V1WorkspaceProfile): V1WorkspaceProfile {
        return {
            ...val,
            plan: (val.plan) ?? "PLAN_TYPE_UNSPECIFIED",
        };
    }

}

export namespace subscription {
    export namespace v1 {
        export interface V1GetSubscriptionResponse {
            subscription?: outputs.subscription.v1.V1Subscription;
        }
        /**
         * v1getSubscriptionResponseProvideDefaults sets the appropriate defaults for V1GetSubscriptionResponse
         */
        export function v1getSubscriptionResponseProvideDefaults(val: V1GetSubscriptionResponse): V1GetSubscriptionResponse {
            return {
                ...val,
                subscription: (val.subscription ? outputs.subscription.v1.v1subscriptionProvideDefaults(val.subscription) : undefined),
            };
        }

        export interface V1Subscription {
            expiresTime?: string;
            plan?: enums.subscription.v1.V1SubscriptionPlan;
            startedTime?: string;
        }
        /**
         * v1subscriptionProvideDefaults sets the appropriate defaults for V1Subscription
         */
        export function v1subscriptionProvideDefaults(val: V1Subscription): V1Subscription {
            return {
                ...val,
                plan: (val.plan) ?? "PLAN_TYPE_UNSPECIFIED",
            };
        }

    }
}
